### ISSUE TITLE
Add TP3 Groovy test cases for Berkeley

### ISSUE THREAD

**Issue by mbroecheler** [thinkaurelius/titan#1006]
there are 2 process and 3 environment tests for groovy (see TinkerGraph tests for comparison) that are not currently invoked in Titan. We should only add those to the berkeley module since passing there should mean everything works correctly.

**Comment by BrynCooke** [comment]
BerkeleyTitanGroovyProcessComputerTest fails due to lack of StandardTitanGraph.empty method.

BerkeleyTitanGroovyEnvironmentTest has a couple of failures:

shouldProcessUTF8Query: TP assigned IDs to vertices https://issues.apache.org/jira/browse/TINKERPOP3-629

shouldEvalGlobalClosuresEvenAfterEvictionOfClass: 
https://issues.apache.org/jira/browse/TINKERPOP3-630

**Comment by BrynCooke** [comment]
Laving open to remind me to remove the empty method in the next TP release.
