### ISSUE TITLE
Port #931 / #973 / #988 from titan05

### ISSUE THREAD

**Issue by dalaro** [thinkaurelius/titan#1074]
These titan05 commits seem to be logically applicable on titan09, but StandardTitanTx has changed too much for a cherry pick to make any sense:
- 43690b3bea97373aca20569e35c442bd4b17289f
- 41fa56113a19a58a4b93cc15c7ad386b98844595
- 4962db3fafb72e31f5d1f77c1c19b520f3feb960
- 84138c642657082101e492941577879225172992
- 879c9a16cddc117291e6bc9e82aa5e76a2666b3c
- 82d629f5c2ec8451858f144b81c13f9494990d6e (#988 / #973, but related)
- dbae2d6d7a14ff16a108ab3f62e8f7233ed0ab50 (#988 / #973, but related)

The other files touched by these commits are generally trivial.  The subtleties seem to be all in STTx.

**Comment by dalaro** [comment]
@mbroecheler you mentioned that this may have already been separately implemented on titan09.  43690b3bea97373aca20569e35c442bd4b17289f introduced the test method `testSettingProperty` and later commits iterated on it; it did not appear to pass in at least two incarnations.  However, I'm uncertain whether that was due to missing functionality in titan09 or a flaw in the test at that specific revision.  It might be worth looking into whether a `testSettingProperty` equivalent for titan09 passes before declaring this done.

**Comment by dalaro** [comment]
Also: 43690b3bea97373aca20569e35c442bd4b17289f introduced MetricsInstrumentedStoreManager to capture metrics on `mutateMany` calls, and that will remain worth retaining even if `testSettingProperty` and the `verifyCardinalityConstraint` bits in STTx fall by the wayside.

**Comment by mbroecheler** [comment]
Yes, keeping the instrumentation around StoreManager and the additional test cases will be critical. What I was trying to say is that the fixes in 84138c642657082101e492941577879225172992 and dbae2d6d7a14ff16a108ab3f62e8f7233ed0ab50 where manually applied to titan09 since the respective logic in StandardTitanTx looks different now.

In many ways this is related to #1070 and we should:
1) Make sure the functionality around metrics is carried over
2) All new test cases and test case updates are carried over
3) Then fix any remaining issues.

Assigning to me for now.

**Comment by mbroecheler** [comment]
dbae2d6d7a14ff16a108ab3f62e8f7233ed0ab50 - manually applied to titan09
82d629f5c2ec8451858f144b81c13f9494990d6e - has been applied to titan09
43690b3bea97373aca20569e35c442bd4b17289f - is now cherry-picked over to titan09
4962db3fafb72e31f5d1f77c1c19b520f3feb960 - has been applied to titan09
84138c642657082101e492941577879225172992 - has been applied to titan09

The following will be ported / adopted as part of #1070:
879c9a16cddc117291e6bc9e82aa5e76a2666b3c
41fa56113a19a58a4b93cc15c7ad386b98844595
