### ISSUE TITLE
Edge/Property ID handling in TP3 IO

### ISSUE THREAD

**Issue by mbroecheler** [thinkaurelius/titan#1083]
Titan's relation ids (i.e. edge and vertexproperty ids) are complex objects since we want to be able to support efficiently retrieving edges by their id, i.e. `g.E(edge.id())` should be an efficient operation. In order to do so, Titan returns a RelationIdentifier object in edge.id() which contains extra information needed to quickly locate the adjacency list and locate the edge within.

However, the information contained in RelationIdentifier are the incident vertex ids and label id which is redundant information if the whole edge is serialized in IO. Effectively, we are representing the edge twice: once in its id and once in the IO serialization.

Questions for @spmallette:
- Is there anything we can do about that in Titan's custom IO serializers? That is, serialize edge ids one way if they are part of the edge and another way if only the id is returned?
- Should we simplify the serialization of RelationIdentifier in GraphSon to be a string that contains all 4 ids rather than a complex object? This would have the advantage that it's easier to consume by a user across different PL. Any downsides to doing this? Gryo makes the assumption to the consumer is in JVM land so it shouldn't be an issue there, right?

**Comment by spmallette** [comment]
> Is there anything we can do about that in Titan's custom IO serializers? That is, serialize edge ids one way if they are part of the edge and another way if only the id is returned?

Let me think on this one....there might be a way to do that if you need to.

> Should we simplify the serialization of RelationIdentifier in GraphSon to be a string that contains all 4 ids rather than a complex object? This would have the advantage that it's easier to consume by a user across different PL. Any downsides to doing this? Gryo makes the assumption to the consumer is in JVM land so it shouldn't be an issue there, right?

The recommendation for GraphSON is to now serialize as a String rather than a complex object (unless the users requests that types be embedded). See the example in `IoTest` and follow that example:

https://github.com/apache/incubator-tinkerpop/blob/28828d4775cc11bcacc710b126e4de4c34fc87b3/gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/structure/IoTest.java#L2428-L2456

As you say and for the reason you say, you should not need to do anything to Gryo.

**Comment by mbroecheler** [comment]
@spmallette Take a look at:
https://github.com/thinkaurelius/titan/blob/titan09/titan-core/src/main/java/com/thinkaurelius/titan/graphdb/tinkerpop/io/graphson/TitanGraphSONModule.java

This is pretty much the same thing that you implemented. And it does to a .toString(). However, when reading graphson, this is being returned:

```
longRepresentation: Array[4]
  0: 5124
  1: 20512
  2: 1045
  3: 4128
relationId: 5124
```

Any idea what might be going on here?

Also, the "withType" implementation looks like it's not writing out the type as in the example you gave, is that correct?

**Comment by spmallette** [comment]
The `serializeWithType` method should look like mine.  That's what gets called when a user requests "type embedding".  When they do that GraphSON can deserialize back to a `EdgeRelation` object.  I assume that since you don't have that, you are getting weirdness in some of the tests. 

Your `serialize` method looks fine assuming that your `EdgeRelation` identifier does the heavy lifting for getting that into the appropriate identifiable format.

**Comment by mbroecheler** [comment]
@rjbriody This should be done in titan09 - please verify that this is what you need.

**Comment by rjbriody** [comment]
@mbroecheler verified. This makes the GraphSON much easier to manage from an application development standpoint.
