### ISSUE TITLE
Cassandra 2.1.x compatibility

### ISSUE THREAD

**Issue by zazzcode** [thinkaurelius/titan#1104]
Datastax community edition now providing Cassandra 2.1.6

For titan 0.9 GA current documentation says 0.9 is compatible with Cassandra 2.0.x.
Can the Cassandra compatibility version be bumped to either 2.x.x or 2.1.x ?

http://planetcassandra.org/cassandra/

**Comment by dalaro** [comment]
reworded title to avoid the verb "Certify", which is a bit loaded

**Comment by dalaro** [comment]
Upgrading from 2.0.8 to 2.1.8 turned out to touch way more parts of Titan than I had anticipated.  The commit log for e5c3421c60934d3fc58b45f69b35884da29eaf60 lists specifics.

The titan-cassandra tests passed when I ran them against 2.1.8 earlier.  I then saw that 2.1.9 was released today.  I committed a patchlevel increment from 2.1.8 -> 2.1.9 as c3bd6b3c53dc6a1194735db03512467baba8f1be.  I'd be surprised if that patchlevel increment broke anything; I only bothered to make sure everything still compiled before pushing the increment commit.
