### ISSUE TITLE
vertex features and custom vertex ids

### ISSUE THREAD

**Issue by dalaro** [thinkaurelius/titan#1133]
This is on the current titan09 HEAD (a0ba586cf56ac191020e113b0661e05aad2f06cd).

@dkuppitz pointed out this behavior:

``` java
gremlin> graph.features().vertex().supportsCustomIds()
==>true
gremlin> graph.addVertex(id, 1)
Vertex does not support user supplied identifiers
Display stack trace? [yN]
```

Titan's `graph.set-vertex-id` still exists, but graph.addVertex does not appear to respect it, despite some sentences in its javadoc comment that talk about validity checking on user-supplied vertex IDs.  I think none of Titan's vertex features check `set-vertex-id`.  Some of Titan's other vertex feature methods also seem to have incorrect behavior, such as:

``` java
gremlin> g.features().vertex().supportsStringIds()
==>true
```

I got confused when I tried to figure out how all of the various vertex features interact.  For example, how precisely does `supportsCustomIds()` differ from `supportsUserSuppliedIds()`?  Only the latter appears in TP3's own unit tests -- maybe the former is something vestigial?  Neither appears in the user documentation.

Some TP3 references:
- Javadoc comment above `Graph.vertices` declaration describing how a subset of vertex features interacts with its method parameters (this is just the read side): https://github.com/apache/incubator-tinkerpop/blob/master/gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/Graph.java#L149-L197
- ElementFeature method declarations (+ their method javadoc): https://github.com/apache/incubator-tinkerpop/blob/master/gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/Graph.java#L571-L619

At this point, I'm pretty confident that at least some of Titan's vertex feature methods are incorrect, but I'm not confident that I understand the semantics of TP3 vertex features well enough to completely correct it.  I would appreciate guidance from @spmallette or @okram.

**Comment by dalaro** [comment]
@dkuppitz says:

> https://github.com/apache/incubator-tinkerpop/blob/master/gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/structure/Graph.java#L726-L742
> anyIds => just eat it
> customIds => eventually allow any id, but validate it first

**Comment by spmallette** [comment]
I guess the javadoc wasn't as clear as I thought.  `supportsUserSuppliedIds` means that a user can specify the identifier - so `g.addV(id,123)` should work.  The other related features:
- `supportsNumericIds`
- `supportsStringIds`
- `supportsUuidIds`
- `supportsCustomIds`
- `supportsAnyIds`

refer to how the id is internally represented in the graph.  So, if you store it as a long, then you should set `supportsNumericIds` to `true`.  If the graph uses a specific custom object for an id, like OrientDBs `RID` (RecordID), then it would set `supportsCustomIds` to `true`.  You only set `supportsAnyIds` to `true` if the graph can take any Java object as an identifier - like TinkerGraph.

I have a tough time writing tests for `supportsCustomIds` because we don't have a graph internally that supports them.

Does that help?  I'll try to tack in some more comments to the javadoc.

**Comment by dalaro** [comment]
Thanks for explaining.  From your comment and a little bit of back and forth in chat, it now sounds like we should do the following in Titan:

Vertex features:
- supportsNumericIds=true
- supportsUserSuppliedIds=[value of graph.set-vertex-id in the underlying config]
- all other vertex feature support methods, including supportsCustomIds=false

Edge features:
- supportsCustomIds=true (because edges are identified by a specific non-numeric, non-UUID, non-String relation ID type)
- all other edge feature support methods=false
