### ISSUE TITLE
Queries not returning any results after inserting new data

### ISSUE THREAD

**Issue by zcox** [thinkaurelius/titan#114]
While evaluating Titan with a local Cassandra backend, I'm having trouble getting any data for some basic queries. Code to reproduce is here:

https://github.com/zcox/titan-scala-test/blob/master/src/main/scala/tweet.scala

Typical sbt console/scala repl output I see is like this:

https://github.com/zcox/titan-scala-test/blob/master/tweet-console-output

With new, empty local Cassandra, set up schema, populate some tweet data, then the queries shown at the end always return empty edge lists & zero edge counts. Could very well be user error on my part but I can't seem to get any data from these queries.

**Comment by mbroecheler** [comment]
Sorry, I missed this issue. From the log output, we can see that the data is written to cassandra, but somehow it is not coming back out. We have a ton of test cases that verify correctness for such simple test queries, so I suspect its something at the scala-java intersection that is causing this because your query looks right to me. Can you try a simple
user.query().count()?

**Comment by mbroecheler** [comment]
Closing the issue for now. Please re-open if the issues persists.
