### ISSUE TITLE
order().by() is broken if the ordered field is part of an ES index

### ISSUE THREAD

**Issue by dkuppitz** [thinkaurelius/titan#1147]
To reproduce:

``` groovy
graph = TitanFactory.open("conf/titan-cassandra-es.properties")
GraphOfTheGodsFactory.load(graph)
g = graph.traversal()
g.V().has("age", inside(1000,5000)).order().by("age", incr)
```

The last line will fail with an exception caused by ES.

**Comment by dalaro** [comment]
This succeeds on ES 1.4.0, but fails on 1.2.1.

The server's error message complains that `unmapped_type` is not a supported option.  This was introduced in ES 1.4.0.  It deprecates the older `ignore_unmapped` option.

I experimented with detecting the version of the cluster nodes using a `NodesInfoRequest`/`NodesInfoResponse` in the java API, and it does seem to be possible, but I thought it wasn't worth the complexity.  Not to mention that rolling upgrades are a thing, and so the results are mutable at runtime.  Instead of trying to do this automatically, I just made a boolean Titan config setting:

```
index.<name>.elasticsearch.use-deprecated-ignore-unmapped-option
```

It defaults to false, which uses the new sort option.  Setting it to true enables sort compatibility with ES cluster versions older than 1.4.0.

The name is ludicrously long, but I also expect this option to be used rarely (if ever), since it only applies to ES versions older than 1.4.0 and enables an option which is deprecated and may eventually be removed.

The change described above is in 5f8ba0e2d5a1db652547384fa868392038ad147a.
