### ISSUE TITLE
TitanPropertiesStep not applied by TitanLocalQueryOptimizerStrategy

### ISSUE THREAD

**Issue by twilmes** [thinkaurelius/titan#1151]
I was profiling Titan 0.9 M2 with query.batch=true and noticed that property retrievals were not being batched.  My simple test query is as follows.

`g.V(4344).out('contains').values('thingType')`

I took a look in TitanLocalQueryOptimizerStrategy and found the TitanPropertiesStep.  The strategy is applying the VertexStep -> TitanVertexStep transformation, but not doing so for the PropertiesStep.  I went ahead and updated it to do this but could not figure out a good non-runtime way to determine if the properties retrieval was going to be against a Vertex or an Edge.  My updates worked as expected and batched the properties retrieval but I figured you guys may have had a reason for not including this initially.  I was hesitant to submit a PR until I figured out a better way to determine if I was operating on a Vertex or Edge and also wanted to see if you guys had another reason for not including this transformation in the optimizer strategy initially.

Thanks,
Ted

**Comment by mbroecheler** [comment]
Excellent point. We had excluded TitanPropertiesStep (i.e. it wasn't applied in any strategy) because we needed additional method access from TinkerPop. That happened but we forgot to add a ticket to re-add TitanPropertiesStep optimizations and hence it never happened.

I have updated TitanPropertiesStep and re-added the optimization. Take a look at 53bb28ad855af750b22eb5f1c3cb0e540852d182 and please make sure this does what you need. We will deploy another 1.0.0-SNAPSHOT soon.

Thanks for pointing this out. That's a good catch for the 1.0 release.

BTW, we won't be optimizing PropertyMapStep until https://issues.apache.org/jira/browse/TINKERPOP3-844 is closed.

**Comment by twilmes** [comment]
I took a look at the commit and reran my tests with the new code and everything looks good.  Property retrievals were batched as expected.  I appreciate you taking a look at this.  It'll be a big help.  As far as the PropertyMapStep goes, that makes sense.  I had been puzzled by the duplication between the PropertiesStep and PropertyMapStep.

Thanks again,
Ted

**Comment by ghost** [comment]
This problem looks like it is now resolved.  Can we close this now ?

**Comment by twilmes** [comment]
Yeah, this has been resolved.  Not sure if it would be a good idea to create a new issue to make sure that when TINKERPOP-844 is finished, any necessary updates will be made.  Although, that'll probably trickle down through the release notes/upgrade instructions with whatever TP release it makes it into.

**Comment by spmallette** [comment]
I would guess that we'd pick that up through the upgrade process. closing - but if you want to create another one referencing that issue then i guess that's cool. up to you....thanks.
