### ISSUE TITLE
Upgrade to Kryo v2

### ISSUE THREAD

**Issue by rand** [thinkaurelius/titan#121]
Upgrading to Kryo v2 for serialization will allow Titan to share JVM with Storm, Cascalog, and a whole host of other recently mature data tools (http://code.google.com/p/kryo/#Projects_using_Kryo).

**Comment by mbroecheler** [comment]
Good point. Since Kryo2 has a different byte format than Kryo1 (https://groups.google.com/forum/?fromgroups=#!topic/kryo-users/lwIoWXBhXXs) this will require a full database upgrade for existing installations. Hence, we are planning this for 0.3 which includes some other incompatible changes and will therefore come with an automatic update process.

**Comment by tvpavan** [comment]
I think 0.3.0 would be good candidate to help interop other data tools. Any plans for this ?
