### ISSUE TITLE
HBase Improvements

### ISSUE THREAD

**Issue by mbroecheler** [thinkaurelius/titan#125]
courtesy of Furcy Pin:

1) You use only one table with up to 5 column families, while the documentation recommends 
here http://hbase.apache.org/book/number.of.cfs.html to keep the number of column families small (no more than 2).

2) The column family names are very long (eg: edgestore, propertyindex), while the documentation
recommends here http://hbase.apache.org/book/rowkey.design.html#keysize.cf to keep
them as short as possible (one character if possible) as they are repeated on every row.
On this point, I understand that your column family names are shared with the Cassandra
implementation, which do not have this issue on column family names, but it would be better 
to have a different naming convention on the HBase side.

3) You generate the table automatically but you do not enable compression on it, while
it could give you a much better efficient storage, and even a faster response time (in particular with Snappy).

**Comment by xedin** [comment]
1. Is not big a deal because first of all having things separated allow to keep track of things independently. You can say the same thing for cassandra but it actually depends on the traffic pattern, compactions should be relatively low concern for us.
2. In current state I don't think it makes sense to change names to one-character or even make them shorter as  this and other HBase housekeeping is relatively low factor comparing to keys/values that we store, grows is mainly driven by data itself.
3. Compression is a trade-off that we shouldn't enforce because depending on the workload it couldn't not be beneficial at all from space/cpu perspective and actually take a way CPU from other parts. That is general problem with block based compression.

**Comment by mbroecheler** [comment]
1. ok
2. I agree that this is not a high priority. In particular, if we enable compression (see below), then this overhead should be negligible.

3) I think we should enable snappy compression by default. The data Titan writes is very amenable to compression (snappy easily compresses to less than 50%) and as such any compression overhead should be made up for by having to read/write less data.

**Comment by xedin** [comment]
Answering on 3) I'm not that sure about 50% compression rate but we can definitely try, the problem with any block level compression is that on some blocks it could actually give you desired ratio but other overhead could actually take even more space than original (Snappy does that). Another important thing to take into account is stealing away CPU time from CPU intensive things like graph walk is not a good trade-off between time & disk space, especially when running on SSDs (with or without RAID, I'm talking about chuck sizes multiple of page size (4KB and higher).

**Comment by xedin** [comment]
Compression was added, closing.
