### ISSUE TITLE
Using Titan as RDF Triplestore

### ISSUE THREAD

**Issue by smyth64** [thinkaurelius/titan#1330]
Hey there!

Me and my team are planning a social network. I'm currently looking for a scalable solution for an RDF Triplestore. Unfortunately all the providers are commercial and want about 10.000$ / year. This is not affordable for our startup ._.

Is there any possibility to use Titan as an RDF Triplestore? My goal is to import the [Wikidata RDF Dump](https://dumps.wikimedia.org/wikidatawiki/entities/).

I think it's possible to use Sesame with Titan?

**Comment by spmallette** [comment]
You can certainly load RDF data into Titan. Of course with Titan 1.0 that supports TinkerPop 3.x and the old Sail based connectors from TinkerPop 2.x in Blueprints are no longer supported so that feature is not available to you. 

In the future, please direct such questions to the Aurelius Mailing List:

https://groups.google.com/forum/#!forum/aureliusgraphs
