### ISSUE TITLE
loading a large gson file into titan is giving timeoutexception

### ISSUE THREAD

**Issue by haritha** [thinkaurelius/titan#1342]
Hi,

I am trying to load a large gson file which has around 15M vertices using the below code. I am using cassandra as the backend. Please help me in resolving this.

 TitanGraph tg = TitanFactory.open(conf);
tg.io(IoCore.graphson()).readGraph("C:/myfile.gson");

I am getting the below error when I run this.

12:33:14,001  INFO Backend:176 - Initiated backend operations thread pool of size 8
12:33:14,035  INFO KCVSLog:730 - Loaded unidentified ReadMarker start time 2016-08-24T07:03:14.035Z into com.thinkaurelius.titan.diskstorage.log.kcvs.KCVSLog$MessagePuller@6676f6a0
12:36:15,371 ERROR StandardTitanGraph:721 - Could not commit transaction [34] due to storage exception in commit
com.thinkaurelius.titan.core.TitanException: Could not execute operation due to backend exception

Caused by: com.thinkaurelius.titan.diskstorage.PermanentBackendException: Permanent failure in storage backend
    at com.thinkaurelius.titan.diskstorage.cassandra.thrift.CassandraThriftKeyColumnValueStore.convertException(CassandraThriftKeyColumnValueStore.java:249)

Thanks

**Comment by spmallette** [comment]
I'm not sure what the problem is offhand and I'm not seeing  where your log output shows a TimeOutException as you indicate in the title. In any case, please send usage questions to the aurelius graphs mailing lists rather than using the issue tracker:

https://groups.google.com/forum/#!forum/aureliusgraphs

You might need to provide a bit more information in your post there and better clarify the error you are getting.
