### ISSUE TITLE
Why standardtitangraph[...] as the toString().

### ISSUE THREAD

**Issue by okram** [thinkaurelius/titan#15]
When using both embedded mode and over Cassandra, Titan's toString() is standardtitan. Can we simply name the graph class TitanGraph so its consistent with other Blueprints implementations?

**Comment by mbroecheler** [comment]
Unlike other blueprints implementation, TitanGraph is not a wrapper around
some native graph implementation. Hence, I made the design choice to have
TitanGraph be an interface and (potentially) have multiple implementations
under it. Based on the configuration that somebody passes to TitanFactory,
the optimal implementation is chosen.
I think this is a better way that asking the user to chose the actual
implementation because it gives us the ability to change behavior without
requiring our users to change anything.

I tried to change the toString method to TitanGraph but then the Blueprints
tests fail because they expect the class name.

On Wed, Jun 6, 2012 at 8:46 AM, Marko A. Rodriguez <
reply@reply.github.com

> wrote:
> 
> When using both embedded mode and over Cassandra, Titan's toString() is
> standardtitan. Can we simply name the graph class TitanGraph so its
> consistent with other Blueprints implementations?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/thinkaurelius/titan/issues/15

## 

Matthias Broecheler, PhD
http://www.matthiasb.com
E-Mail: me@matthiasb.com

**Comment by okram** [comment]
What about having StandardTitanGraph be called TitanGraph, but it is in a different package so its com.thinkaurelius.anotherpacker.TitanGraph? ... :D

**Comment by mbroecheler** [comment]
Haha, in that case I'd rather change the toString method and exclude the
blueprints test case checking it.

On Wed, Jun 6, 2012 at 10:30 AM, Marko A. Rodriguez <
reply@reply.github.com

> wrote:
> 
> What about having StandardTitanGraph be called TitanGraph, but it is in a
> different package so its com.thinkaurelius.anotherpacker.TitanGraph? ... :D
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/thinkaurelius/titan/issues/15#issuecomment-6157046

## 

Matthias Broecheler, PhD
http://www.matthiasb.com
E-Mail: me@matthiasb.com

**Comment by okram** [comment]
this has been fixed. closing.
