### ISSUE TITLE
Fix the toString() of TitanGraph.

### ISSUE THREAD

**Issue by okram** [thinkaurelius/titan#172]
gremlin> g = TitanFactory.open(conf)
==>titangraph[com.thinkaurelius.titan.diskstorage.cassandra.thrift.CassandraThriftStoreManager:localhost]

that should be, at minim:

class.getName().toLowerCase()

==>titangraph[cassandrathriftmanager:localhost]

**Comment by xedin** [comment]
This is actually fixed in master.

gremlin> g = TitanFactory.open('titan.properties')
13/03/18 14:47:00 INFO impl.ConnectionPoolMBeanManager: Registering mbean: com.netflix.MonitoredResources:type=ASTYANAX,name=ClusterTitanConnectionPool,ServiceType=connectionpool
13/03/18 14:47:00 INFO impl.ConnectionPoolMBeanManager: Registering mbean: com.netflix.MonitoredResources:type=ASTYANAX,name=KeyspaceTitanConnectionPool,ServiceType=connectionpool
==>titangraph[astyanax:127.0.0.1]

gremlin> g = TitanFactory.open('titan.properties')
==>titangraph[cassandrathrift:127.0.0.1]
