### ISSUE TITLE
Data Types of Key Indices

### ISSUE THREAD

**Issue by spmallette** [thinkaurelius/titan#18]
Consider making key indices more forgiving when it comes to data types.  For instance:

``` text
gremlin> conf = new BaseConfiguration()
==>org.apache.commons.configuration.BaseConfiguration@3f72c47b
gremlin> conf.setProperty("storage.backend", "cassandra")
==>null
gremlin> conf.setProperty("storage.hostname", "127.0.0.1")
==>null
gremlin> g  = TitanFactory.open(conf)
==>standardtitangraph[cassandra]
gremlin> g.createKeyIndex("longIndex", Vertex.class)
==>null
gremlin> g.createKeyIndex("integerIndex", Vertex.class)
==>null
gremlin> g.stopTransaction(SUCCESS)
==>null
gremlin> v = g.addVertex(null)
==>v[4]
gremlin> v.setProperty("longIndex", 1000l)
==>null
gremlin> v.setProperty("integerIndex", 1000)
==>null
gremlin> g.stopTransaction(SUCCESS)
==>null
gremlin> g.V("longIndex", 1000)
gremlin> g.V("longIndex", 1000l)
==>v[4]
gremlin> g.V("integerIndex", 1000)
==>v[4]
gremlin> g.V("integerIndex", 1000l)
gremlin>
```

It might be good to just treat integers/longs as general numerics so that it doesn't create confusion for new users.

**Comment by mbroecheler** [comment]
Since Blueprints has no notion of data type, Titan accepts arbitrary objects and then stores the object class with the attribute so it can deserialize them. When it does so, an integer != long even if their value is the same, which is why you see this behavior.
When explicitly defining a key, the user provides a data type and then only those types are accepted.

What I could do for the standard Blueprints case is that I cast ints to longs and floats to doubles explicitly before storing them. That would require extra storage space, but if that is of concern than one should use TypeMaker anyways. WDYT?

**Comment by mbroecheler** [comment]
So, I implemented automatic type conversion for int->long and float->double when the data type is explicitly configured for a key. For the general Blueprints data type Object.class this cannot be done, because some test cases expect the original int value and not a long, so the Blueprints tests fail.

**Comment by spmallette** [comment]
Cool...I think a good portion of users will appreciated the simplicity and convenience of this change.
