### ISSUE TITLE
[0.2.0-berkely] ID renewal thread did not complete in time.

### ISSUE THREAD

**Issue by fabiankessler** [thinkaurelius/titan#182]
I got this 2-3 times, randomly: 
Caused by: java.lang.IllegalStateException: ID renewal thread did not complete in time.

The setup is very basic: an embedded berkely db, fresh and empty (deleted all db files after each run). a unit test that creates a couple entities.

If you need more info then I'll copy the stack trace next time and tell more about the code. It's not reproducible.

**Comment by mbroecheler** [comment]
Are you creating a lot of vertices and edges in a short amount of time?
That triggers a lot of id acquisitions which might fail if the BerkeleyDB
instance is under a lot of load because they time out.
Try to increase the id block size by a factor of 10 or 100 when you do
insertion heavy things. See if that solves it.

HTH,
Matthias

On Tue, Mar 19, 2013 at 10:02 AM, Fabian Kessler
notifications@github.comwrote:

> I got this 2-3 times, randomly:
> Caused by: java.lang.IllegalStateException: ID renewal thread did not
> complete in time.
> 
> The setup is very basic: an embedded berkely db, fresh and empty (deleted
> all db files after each run). a unit test that creates a couple entities.
> 
> If you need more info then I'll copy the stack trace next time and tell
> more about the code. It's not reproducible.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/thinkaurelius/titan/issues/182
> .

## 

Matthias Broecheler
http://www.matthiasb.com

**Comment by fabiankessler** [comment]
No, it was just a couple of entities. Under 100. I had this in my persistence tests around every 7th time (wild guess). I have now upgraded to 0.3.1 and haven't seen it anymore...
