### ISSUE TITLE
Sub-type not accepted for Property type values

### ISSUE THREAD

**Issue by jarohen** [thinkaurelius/titan#183]
I created a indexed key of type java.lang.Number but then couldn't create values of type long or int - trying to add such a property to a vertex was failing with (for example):

`'java.lang.IllegalArgumentException: Value [12] is not an instance of the expected data type for property key [test-num]. Expected: class java.lang.Number, found: class java.lang.Long'`

Is this intended behaviour? If not, I think it's a pretty quick fix to com.thinkaurelius.titan.graphdb.relations.AttributeUtil/checkAttributeType - changing `datatype.equals(attribute.getClass())` to `datatype.isAssignableFrom(attribute.getClass())`

Thanks!

**Comment by mbroecheler** [comment]
Yes, this is intended behavior. The reason is that if you declare a type,
titan does not write out the type information but just the type data. So,
if you declare dataType(Long.class) it will just write a single 8 byte long
value to disk. If you declare dataType(Object.class) it will have to write
a class header so that titan knows what the type is adding significant
overhead.
That said, if you declare Number.class then Titan does not know whether to
expect an int or long or double, etc.

Hence, if you declare a type, titan is strict about checking it.
HTH,
Matthias

On Thu, Mar 21, 2013 at 7:03 AM, James Henderson
notifications@github.comwrote:

> I created a indexed key of type java.lang.Number but then couldn't create
> values of type long or int - trying to add such a property to a vertex was
> failing with (for example):
> 
> 'java.lang.IllegalArgumentException: Value [12] is not an instance of the
> expected data type for property key [test-num]. Expected: class
> java.lang.Number, found: class java.lang.Long'
> 
> Is this intended behaviour? If not, I think it's a pretty quick fix to
> com.thinkaurelius.titan.graphdb.relations.AttributeUtil/checkAttributeType
> - changing java datatype.equals(attribute.getClass()) to java
>   datatype.isAssignableFrom(attribute.getClass())
> 
> Thanks!
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/thinkaurelius/titan/issues/183
> .

## 

Matthias Broecheler
http://www.matthiasb.com

**Comment by mbroecheler** [comment]
I have updated the documentation to better expose this:
https://github.com/thinkaurelius/titan/wiki/Titan-Limitations
