### ISSUE TITLE
Astyanax connection issue

### ISSUE THREAD

**Issue by mbroecheler** [thinkaurelius/titan#202]
I am not entirely sure what the issue was with astyanax. We were able to run Titan with "cassandra" as a backend  from  the cassandra nodes, but if we did tried remotely it would get stuck trying to establish a connection. We confirmed that the right ports were open on the nodes, both UDP and TCP. Then I saw in one of your posts to the mailing list the suggestion of trying with "cassandrathrift" to someone also having connectivity issues in Rackspace, and using this backend worked right away.

Both backends worked fine when using virtualbox instead of EC2,  so we suspect this might be some networking issue. .

**Comment by xedin** [comment]
I have played with it for a while and I think that the problem here is how we ask it to discover hosts. NodeDiscoveryType is set to RING_DESCRIBE by default (via "node-discovery-type") which means that Astyanax would try to call "describe_ring(keyspace)" to identify hosts available for client requests, I think in ec2 case it just takes to long to calculate ring state which results in global connection pool timeout. As we already require to provide hostnames in titan properties we can switch it to NONE by default (as well as connection pool type to BAG, to let Cassandra route for us) to use that list instead of trying to do fancy things.

**Comment by xedin** [comment]
I have also started working on upgrading Astyanax to the latest version which is currently 1.56.37, that officially supports Cassandra 1.2.x

**Comment by okram** [comment]
Note that I see this issue happen "randomly" on EC2. I tend to use Astyanax and then, sometimes, when it just hangs, I then move to Thrift and proceed with what I am doing.

**Comment by xedin** [comment]
Pull is at https://github.com/thinkaurelius/titan/pull/234
