### ISSUE TITLE
adding properties in one transaction, after deleting them in another, brings the vertices back

### ISSUE THREAD

**Issue by bdeggleston** [thinkaurelius/titan#214]
see the failing test case here:

https://gist.github.com/bdeggleston/5320562

I would expect an error to be raised when tx2 is committed

**Comment by mbroecheler** [comment]
This is a really tricky one. I have been giving this a good amount of thought over the last two weeks. Here is the thing: In order to "fix" this, we would have to check if a vertex still exists every time we mutate the vertex. That is obviously very costly and not feasible at scale. In particular, because one would have to acquire some sort of lock to ensure that no race conditions arise. That makes it even more expensive.

Rather, I would suggest focusing on a "clean-up" solution. Every vertex has a "secret" property to indicate its existence. That also gets deleted when the vertex is deleted. Adding properties/edges after that won't bring that property back. Hence, its easy to identify deleted vertices that have become phantoms and delete them with a sweeping Faunus job.

If you want to make absolutely sure that deleted vertices don't magically reappear, then create a out-unique property "besafe" which has locking enabled and Integer.class as datatype. When you initially create the vertex do a v.setProperty("besafe",1). Every time you mutate the vertex, do v.setProperty("besafe",v.getProperty("besafe")+1). This will use Titan's locking mechanism to ensure no phantom vertices. However, as mentioned above, this is VERY expensive. 

I have changed this ticket to "question". Let's talk about it ;-)

**Comment by mbroecheler** [comment]
@bdeggleston : Does Titan tools help with cleaning up such vertices? I saw its part of the documentation: 
https://github.com/StartTheShift/titan-tools

**Comment by bdeggleston** [comment]
@mbroecheler, yes Titan tools does clean up vertices that are missing the VertexState property.

Since each titan "client" working on the storage backend doesn't talk to the other clients, has authoritative control over the data, and the data backend has no understanding of the graph it's storing, it's probably unavoidable that phantom properties will pop up occasionally. The "edge only exists on one vertex" problem is probably also related to this. So being able to periodically cleanup the dataset would be a good idea.

That said, what if we checked for consistency on reads? If I remember correctly, doesn't Titan check for the existence of vertices by checking that their key exists? How big a deal would it be to check for key->VertexState exists instead of just the key? I'm assuming that performing edge traversals ignores the vertex properties and goes straight to taking a slice of the edges, so there would be a performance penalty. However, if this was configurable behavior, people would have the choice between speed or consistency. We could even have something like a vertex read repair chance, where we take a close look at some % of vertices and repair any problems we find.

**Comment by mbroecheler** [comment]
Yes, its a good idea to check for the existence of VertexState instead of
just the key. It'll be a little slower, but I guess it wouldn't be too bad
- we'll have to test that one.

While that would be more robust, phantom vertices can still arise when the
deletion and modification happen virtually at the same time. So, clean up
will always be necessary. Unless you lock which I wouldn't even want to
advertise as an option because of its terrible performance implications. If
that is desirable, a user should use a consistent backend like BerkeleyDB.

On Sat, May 4, 2013 at 10:16 AM, Blake Eggleston
notifications@github.comwrote:

> @mbroecheler https://github.com/mbroecheler, yes Titan tools does clean
> up vertices that are missing the VertexState property.
> 
> Since each titan "client" working on the storage backend doesn't talk to
> the other clients, has authoritative control over the data, and the data
> backend has no understanding of the graph it's storing, it's probably
> unavoidable that phantom properties will pop up occasionally. The "edge
> only exists on one vertex" problem is probably also related to this. So
> being able to periodically cleanup the dataset would be a good idea.
> 
> That said, what if we checked for consistency on reads? If I remember
> correctly, doesn't Titan check for the existence of vertices by checking
> that their key exists? How big a deal would it be to check for
> key->VertexState exists instead of just the key? I'm assuming that
> performing edge traversals ignores the vertex properties and goes straight
> to taking a slice of the edges, so there would be a performance penalty.
> However, if this was configurable behavior, people would have the choice
> between speed or consistency. We could even have something like a vertex
> read repair chance, where we take a close look at some % of vertices and
> repair any problems we find.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/thinkaurelius/titan/issues/214#issuecomment-17437777
> .

## 

Matthias Broecheler
http://www.matthiasb.com
