### ISSUE TITLE
Titan 0.3.0 can read a Titan 0.2.0 backend (BerkeleyDB)

### ISSUE THREAD

**Issue by okram** [thinkaurelius/titan#216]
I thought looking at a Titan 0.2.0 backend with Titan 0.3.0 would cause an exception due to the version change.

NOTE: The NullPointerException below is a demonstration of #200 ticket.

``` groovy
gremlin> g = TitanFactory.open('/tmp/test020')
==>titangraph[local:/tmp/test020]
gremlin> g.V.count()
java.lang.NullPointerException
Display stack trace? [yN]
gremlin> g.V[0..10].count()
==>11
gremlin> g.shutdown()
==>null
gremlin> g = TitanFactory.open('/tmp/test030')
==>titangraph[local:/tmp/test030]
gremlin> g.V[0..10].count()
==>11
gremlin> g.shutdown()
==>null
gremlin> quit
```

**Comment by xedin** [comment]
Which branch did you use and when your dataset was created? 

What I did:
1. git checkout titan02
2. mvn clean package -Dmaven.test.skip=true
3. created graph of god following the old wiki (TitanFactory.open('/tmp/titan02'); createIndex(...), g.loadGraphML(...))
4. git checkout titan03
5. mvn clean package -Dmaven.test.skip=true
6. Tried to open /tmp/titan02 graph
   gremlin>  g = TitanFactory.open('/tmp/titan02')
   StorageBackend is incompatible with Titan version: 0.3.1-SNAPSHOT vs. 0.2.2-SNAPSHOT
   Display stack trace? [yN] n

So 0.3 branch actually prevents you from opening old BerkleyJE directories...

Also following #200 I tried g.V.has('type', 'god') and it returned me vertices without a problem on 0.3.

**Comment by mbroecheler** [comment]
Titan 0.2.0 did not write version information to the database when it was released. That feature was only added later. Hence, when you open such a database with Titan 0.3.x or 0.2.1+ it will try to open it since it does not know any better and then fail when trying to actually read anything.

Nothing we can do about it. Later versions of Titan will check for version compatibility.
