### ISSUE TITLE
Connection-timeout parameter not working ?

### ISSUE THREAD

**Issue by okram** [thinkaurelius/titan#241]
Hi,

I set this to 60000 (60 seconds):

``` text
storage.connection-timeout   Default time out in milliseconds after which to fail a connection attempt with a Cassandra node     Integer     10000   Yes
```

And I still get ConnectionRefused exceptions in less than 10 seconds.

**Comment by mbroecheler** [comment]
I think those two are different things. You get a ConnectionRefused if the server blocks your connection attempt. In that case, there is no reason to wait before throwing the exception.

The connection timeout is used so that the client can determine at which point the lack of response from the server ought to be interpreted as a failed connection.
