### ISSUE TITLE
Index-free adjacency

### ISSUE THREAD

**Issue by protheusfr** [thinkaurelius/titan#244]
Just a question, is Titan index-free adjacency when using Cassandra backend ?
If not what is the graph traversal cost order ? ( O(1) ? O log(N) ? ...)

**Comment by okram** [comment]
Looking up a vertex ID by its long is a O(1) operation (a hash). Thus, that gets you vertex A (lets say). Then the next cost is how to get to B. Well you need to find an edge in A that leads to B. If you have a small edge set, then its O(1) + O(m) + O(1). Thus, O(m), where m is the number of incident edges you scanned off of A. The problem is that m can be very large -- e.g. super nodes. In this situation, you need an index into that |m| set.  See:

  http://thinkaurelius.com/2012/10/25/a-solution-to-the-supernode-problem/

**Comment by protheusfr** [comment]
Thank's for response, I'm perfectly concerned by super node problem... 

Bastien VIGNERON

**Comment by okram** [comment]
Note that Titan provides vertex-centric indices which alleviate the super node problem.

```
https://github.com/thinkaurelius/titan/wiki/Vertex-Centric-Indices
```
