### ISSUE TITLE
Exception message -- value -> key

### ISSUE THREAD

**Issue by okram** [thinkaurelius/titan#249]
" java.lang.IllegalArgumentException: The given value is already used as a property"

This should read "The given key is already used as a property"

key/value is the terminology for TinkerPop property graph model.

**Comment by mbroecheler** [comment]
Actually, in this particular instance its referring to the value already being used since the key is defined as in-unique, i.e. values for that key must be globally unique. I have changed the message to make that clearer:
"The given value is already used as a property and the property key is defined as in-unique"
