### ISSUE TITLE
LockKeyColumnValueStoreTest assertion failures

### ISSUE THREAD

**Issue by mbroecheler** [thinkaurelius/titan#264]
when running against embedded cassandra:

There are many entries in the log file of the type:

``` text
10422 [main] WARN  com.thinkaurelius.titan.diskstorage.locking.consistentkey.ConsistentKeyLockTransaction  - Discarded expired lock with timestamp 1367866631286268000
10423 [main] ERROR com.thinkaurelius.titan.diskstorage.locking.consistentkey.ConsistentKeyLockTransaction  - Failed to locally unlock LockClaim [backer=com.thinkaurelius.titan.diskstorage.locking.consistentkey.ConsistentKeyLockStore@7ddc6a9d, key=0x6b6579, col=0x6b6579, expectedValue=null]
java.lang.AssertionError
        at com.thinkaurelius.titan.diskstorage.locking.consistentkey.LocalLockMediator.unlock(LocalLockMediator.java:141)
```

and for line 137 generated during tearDown().

**Comment by dalaro** [comment]
Here are my preliminary thoughts.  Since the locking code is delicate and has undergone refactoring since I last worked on it, I'm planning to take a break and examine this again later today.  However, I think I see two causes of the assertion failures.
1. Multiple calls to commit() on the same transaction.  When executing the test methods testLocalLockContentention() and expectedValueMismatchCausesMutateFailure(), tx[0][0].commit() is called once at the end of the test function and again during close().
2. Committing a transaction with expired locks.  This happens in relockExtendsLocalExpiration() and expiredLocalLockIsIgnored().

A related concern: I think relockExtendsLocalExpiration() is buggy and passes by accident.  Repeatedly calling LocalLockMediator#lock does extend expiration, but repeatedly calling StorageManager#acquireLock does not extend expiration.  I'll revisit this point when I come back to the locking code.

**Comment by dalaro** [comment]
In 74166f9, I fixed code in ConsistentKeyLockTransaction where we committed twice (cause 1) by removing the redundant commit.  An alternative approach to cause 1 which I briefly considered but did not pursue: make commit completely idempotent besides perhaps logging an error on calls after the first.  I didn't want to fiddle with transaction semantics close to a release, even if the change seemed harmless.

I corresponded with Matthias about test failures related to expired locks (cause 2).  We agreed that the relockExtendsLocalExpiration() test method is looking for an unnecessary feature that isn't actually expected or used in titan proper.  At some point, we entertained allowing extension of a lock's expiration time by calling acquireLock() again before it times out.  relockExtendsLocalExpiration() attempts to verify this unimplemented lock expiration extension feature.  But titan never actually uses this feature, and the current behavior of subsequent acquireLock() calls doing nothing is easier to debug and think about.  I changed the unit test to verify the actual behavior.

The assertion during tearDown() after expiredLocalLockIsIgnored() was trying to warn the user about expired locks, but the assertion message was almost useless for that goal.  Assertion is also inappropriately strong for expired locks.  I changed the two assertion sites in LocalLockMediator#unlock() into conditionals that log ERRORs when triggered and cause unlock to return false.
