### ISSUE TITLE
Properties indexed by elasticsearch are sometimes nulled out when the vertex is retrieved

### ISSUE THREAD

**Issue by mdessureault** [thinkaurelius/titan#294]
Environment:
Titan 0.3.1 running cassandra and elasticsearch in embedded mode on a single Redhat server.

Here is a code snippet that reproduces the problem:

``` java
RexsterClient client = RexsterClientFactory.open("localhost", 8184, "graph");
client.execute("g.makeType().name('objectType').dataType(String.class).indexed('search', Vertex.class).unique(Direction.OUT).makePropertyKey()");
client.execute("g.makeType().name('uid').dataType(Long.class).indexed('search', Vertex.class).unique(Direction.OUT).makePropertyKey()");
rexster.execute("g.commit()");
List<Object> response = client.execute("v = g.addVertex(['uid':167774517,'ipv4Addr':'10.0.9.53','cid':2,'objectType':'NetworkSensor','observationDomain':0]); v");
System.out.println(response);
rexster.execute("g.commit()");
```

This prints the following:

``` java
[{_properties={uid=167774517, ipv4Addr=10.0.9.53, objectType=NetworkSensor, cid=2, observationDomain=0}, _id=40, _type=vertex}]
```

Retrieving this vertex either using gremlin or rexster works as expected.

Using gremlin:

```
gremlin> g.v(40).map
{uid=167774517, ipv4Addr=10.0.9.53, objectType=NetworkSensor, cid=2, observationDomain=0}
```

Using rexster:

```
http://localhost:8182/graphs/graph/vertices/40
==>{ version: "2.3.0", results: { uid: 167774517, ipv4Addr: "10.0.9.53", objectType: "NetworkSensor", cid: 2, observationDomain: 0, _id: 40, _type: "vertex" }, queryTime: 7.630346 }
```

But if I want to retrieve all vertices, the objectType (and sometimes the uid) properties get nulled out. These properties use elasticsearch for their index.

Using gremlin:

```
gremlin> g.V.map
==>{uid=null, ipv4Addr=10.0.9.53, objectType=null, cid=2, observationDomain=0}
```

_Note the null uid and objectType._

Using rexster:

```
http://localhost:8182/graphs/graph/vertices
{ version: "2.3.0", results: [ { uid: 167774517, ipv4Addr: "10.0.9.53", objectType: null, cid: 2, observationDomain: 0, _id: 40, _type: "vertex" } ], totalSize: 1, queryTime: 23.945193 }
```

_Note the null objectType._

**Comment by mbroecheler** [comment]
I cannot reproduce this behavior in a Titan only environment (i.e. without Rexster involved) which caused me to hit my head against the wall quite a bit.
I think I have a reasonable explanation for why this is happening: Each statement send to through the client gets treated independently. That means, the g.commit() after the first two type definition statement may not actually commit those. So, when you then define the vertex, it will automatically create the types which will then (maybe on the 2nd commit) get overwritten which causes the null returns.

@spmallette Is this at all realistic?

**Comment by mbroecheler** [comment]
Pending further notice moved to 0.4.1

**Comment by spmallette** [comment]
Using RexsterClient in that fashion represent sessionless calls and therefore each is treated independently.  By luck I suppose it might work if the same thread processed each request on the server, but that's unlikely.  Several possible solutions:

*.Issue those commands as one complete request (i.e. the two typemaker requests and the `commit()`)
- Issue those commands in a session through `RexsterClient`.  You will have to construct your own `RexsterMessage` objects and manage your session identifier manually. https://github.com/tinkerpop/rexster/blob/master/rexster-protocol/src/main/java/com/tinkerpop/rexster/client/RexsterClient.java#L110
- Issue those commands statically from a Gremlin prompt when your Graph gets initialized. I don't know your use case, but I prefer this option overall.  I feel as though TypeMaker work is generally administrative and hands-on and best managed in a manual way.

Since @mbroecheler could not recreate this problem without Rexster, I think this is a non-issue for Titan.
