### ISSUE TITLE
Edges and properties not resolved correctly when removed

### ISSUE THREAD

**Issue by mbroecheler** [thinkaurelius/titan#314]
Same with "normal" edges:

gremlin> g = TitanFactory.open('/tmp/bar')
==>titangraph[local:/tmp/bar]
gremlin> t = g.makeType().name("type").dataType(Integer.class).unique(OUT).indexed(Edge.class).makePropertyKey()
==>v[36028797018963978]
gremlin> g.makeType().name("friend").primaryKey(t).makeEdgeLabel()
==>v[36028797018963990]
gremlin> g.commit()
==>null
gremlin> v1 = g.addVertex(null)
==>v[4]
gremlin> v2 = g.addVertex(null)
==>v[8]
gremlin> v1.addEdge("friend", v2).setProperty("type", 0)
==>null
gremlin> g.commit()
==>null
gremlin> v1.outE("friend").inV().filter{ it == v2 }.back(2).sideEffect{ it.setProperty("type", 1) }
==>e[l-4-2F0LaTPQAS][4-friend->8]
gremlin> g.commit()
Could not commit transaction due to exception during persistence
Display stack trace? [yN]
I've tried a lot of things, but didn't find any workaround. It's not even possible to remove (and recreate) the edge.

**Comment by violahs** [comment]
I have been having trouble deleting nodes from titan,  and I noticed that this same process leads to failure on remove as well:

[~/Packages/titan-berkeleyje-0.3.1]$ bin/gremlin.sh 

```
     \,,,/
     (o o)
```

-----oOOo-(_)-oOOo-----
gremlin> Gremlin.version()
Gremlin.version()
==>2.3.0
gremlin> Titan.version()
Titan.version()
==>0.3.1
gremlin> g = TitanFactory.open('/tmp/bar')
==>titangraph[local:/tmp/bar]
gremlin> t = g.makeType().name("type").dataType(Integer.class).unique(OUT).indexed(Edge.class).makePropertyKey()
==>v[36028797018963978]
gremlin> g.makeType().name("friend").primaryKey(t).makeEdgeLabel()
==>v[36028797018963990]
gremlin> g.commit()
==>null
gremlin> v1 = g.addVertex(null)
==>v[4]
gremlin> v2 = g.addVertex(null)
==>v[8]
gremlin> v1.addEdge("friend", v2).setProperty("type", 0)
==>null
gremlin> g.commit()
==>null
gremlin> g.V.remove()
==>null
gremlin> g.commit()
Could not commit transaction due to exception during persistence
Display stack trace? [yN] 
gremlin> g.commit()
g.commit()
==>null
gremlin> g.V.count()
g.V.count()
==>2
gremlin> g.V
g.V
==>v[4]
==>v[8]
gremlin>
