### ISSUE TITLE
.\bin\gremlin.bat path issues

### ISSUE THREAD

**Issue by jmzhang** [thinkaurelius/titan#316]
I'm fairly new to windows scripting stuff. After downloading the titan on windows, I've be struggling to start the gremlin and create a titan graph. Finally, I figured out that I have to start gremlin one level out of the .\bin folder by typing ".\bin\gremlin.bat" in the command prompt and the gremlin.bat needs a little modification as below:

change `set LIBDIR=..\lib` to  `set LIBDIR=.\lib`

change 

```
:concatsep

if "%CP%" == "" (

set CP=%LIBDIR%\%1

)else (

set CP=%CP%;%LIBDIR%\%1

)
```

to 

```
:concatsep

if "%CP%" == "" (

set CP=%1

)else (

set CP=%CP%;%1

)
```

Otherwise, there will be various path issues within the gremlin. Hope someone will fix this issue and new comers on windows might find it helpful.

**Comment by spmallette** [comment]
thanks. i'll look into these suggested changes.  the .bat was based on the Gremlin version, so I'll adjust it there as well if necessary.

**Comment by spmallette** [comment]
I wish i'd kept better notes on this because I gave this fix a try and while it does get things to run properly if you are running as `bin\gremlin.bat` it won't work as it always has from within the `bin`.  My .bat scripting is not so good and couldn't get the stupid thing to be nice so that it could work either way.  I'd rather not trade one problem for another especially since i think people are used to it starting the other way for all this time.  @jmzhang any ideas how to make it worth both ways?

**Comment by spmallette** [comment]
i would assume that most windows users are calling the .bat the "correct" way.  closing since a clear fix to have it run both ways was not provided.
