### ISSUE TITLE
Create a general interface (and subsequent implementations) for linearly scanning key/values out of Titan

### ISSUE THREAD

**Issue by okram** [thinkaurelius/titan#319]
If Titan had a general interface for scaning data, then we could simply have TitanInputFormat in Faunus and other Titan implementations (e.g. LevelDB :)) could be subjected to analysis from Faunus.

**Comment by mbroecheler** [comment]
I am not sure if it makes sense to expose this through Titan since it will
be faster for Faunus to directly go against the underlying store an have
Titan act as the "translator". When we pull titan-core under Faunus, this
will be pretty easy and reduce a lot of code.
For the smaller, local machine systems we can use Titan's optimized g.V and
work with Furnace directly.

On Tue, Jul 9, 2013 at 8:03 AM, Marko A. Rodriguez <notifications@github.com

> wrote:
> 
> If Titan had a general interface for scaning data, then we could simply
> have TitanInputFormat in Faunus and other Titan implementations (e.g.
> LevelDB :)) could be subjected to analysis from Faunus.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/thinkaurelius/titan/issues/319
> .

## 

Matthias Broecheler
http://www.matthiasb.com
