### ISSUE TITLE
ConsistentKeyLockTransaction - Discarded expired lock with timestamp

### ISSUE THREAD

**Issue by vikraman** [thinkaurelius/titan#324]
I get these logs with the same timestamp everytime a transaction is committed.

```
2013-07-18 09:03:40,835 WARN  c.t.t.d.l.c.ConsistentKeyLockTransaction - Discarded expired lock with timestamp 1374117566873891014
2013-07-18 09:03:40,835 WARN  c.t.t.d.l.c.ConsistentKeyLockTransaction - Discarded expired lock with timestamp 1374117764852924118
```

I am using `0.3.2-SNAPSHOT`, and lots of concurrent multi-threaded transactions.

**Comment by dalaro** [comment]
Titan's current lock code never deletes expired locks.  Leaked locks (e.g. due to a client crash) are bound to reach this expiration time and start generating these warnings.  These lock columns could be manually deleted, but there's no automatic mechanism for it yet.

I should probably add an option to automatically log and then delete expired locks.  I haven't thought carefully about it yet, but my I'm considering a daemon thread to avoid complicating the lock acquire or check paths.  Maybe it should be disabled by default.

**Comment by jcamins** [comment]
Are there any negative effects from these errors? How would I delete them manually?

**Comment by mbroecheler** [comment]
No, there should be no negative effects. The abandoned locks will
eventually time out.

**Comment by dalaro** [comment]
I implemented an optional background service that logs and deletes expired locks.

This is subject to refactoring, but here's how it works now.  It's backed by an executor with zero idle threads, a maximum of one background thread, and a five second thread keepalive.  When ConsistentKeyLockTransaction discovers an expired lock, it calls LockCleanerService.clean(KeyColumn, long cutoffTimestamp, StoreTransaction).  This is "fire and forget" from the consistent key locker's point of view.  The LockCleanerService implementation keeps a 30-second expiring cache as a cooldown mechanism to prevent a flurry of redundant clean(...) invocations from swamping its executor.  Requests to clean KeyColumns present in the expiring cache are logged and dropped without executing.   Otherwise, when putIfAbsent(...) on the expiring cache returns no existing KeyColumn entry, the a cleaner runnable is submitted to the executor and eventually runs in a daemon thread.

The config option, in an attempt to match the naming pattern of existing locking-related config options, is `storage.lock-clean-expired=<boolean>`.

The design would be cleaner if the runnable opened a new StoreTransaction from the StoreManager rather than piggybacking on the tx used by ConsistentKeyLocker's methods, but for HBase and Cassandra "transactions" where this is useful it doesn't really matter.  It's also OK if the CKL tx closes while we're attempting to delete expired locks, since these runnables can fail at any point in their execution without harming the system.

Related commits:
- 68825b885c5f6290c72a4502ad2318ac35becb90
- 835163ca6a2c495959cdba70f9828eff2b068537
- 2812aed15d71be3fb5c4739ddd002c93a8e18407
