### ISSUE TITLE
When previous session disconects without commit, commit fails

### ISSUE THREAD

**Issue by TimLudwinski** [thinkaurelius/titan#375]
Doing the following in Python

```
from rexpro import RexProConnection
conn = RexProConnection('localhost', 8184, 'graph')

conn.execute('g.V.remove()') #Or other changes

#Exit program without commit
```

Causes the following to fail until the server is restarted

```
g = rexster.getGraph('graph')

g.V.remove()
g.commit()
```

with the error message:

13/09/20 15:42:00 WARN filter.ScriptFilter: Could not process script [g.commit()] for language [groovy] on session [[B@33fca8e4] and request [[B@10b42b66]
==>An error occurred while processing the script for language [groovy]. All transactions across all graphs in the session have been concluded with failure: java.util.concurrent.ExecutionException: javax.script.ScriptException: javax.script.ScriptException: com.thinkaurelius.titan.core.TitanException: Could not commit transaction due to exception during persistence

**Comment by TimLudwinski** [comment]
NOTE: I'm using the BereleyDB backend.

**Comment by mbroecheler** [comment]
This might be because the transaction handle inside BerkeleyDB from the
previous transaction is still lingering around causing the failure. Hard to
tell without the entire stack trace - could you retrieve that from the logs?

THanks,
Matthias

On Friday, September 20, 2013, TimLudwinski wrote:

> NOTE: I'm using the BereleyDB backend.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/thinkaurelius/titan/issues/375#issuecomment-24837015
> .

## 

Matthias Broecheler
http://www.matthiasb.com

**Comment by TimLudwinski** [comment]
Sure, I can reproduce this bug pretty easily.  I won't be in the office
until Monday though.

Tim

**Comment by spmallette** [comment]
@bdeggleston are requests in rexpro-python configured to auto-commit by default?

**Comment by TimLudwinski** [comment]
I can duplicate this just using the rexster console.  I'm not sure how to get an entire stack trace.  Titan doesn't seem to be logging anywhere else except the console (which doesn't show any message besides the WARN message above).  (BTW, the second part of the error above starting with ==> comes from the rexster console).

**Comment by spmallette** [comment]
can you clarify how you do this with rexster console?  are the repo steps:
1. open a rexster console and connect to a berkeleydb instance hosted in rexster
2. add a vertex but don't commit()
3. kill rexster console
4. restart rexster console
5. try to mutate the graph....error

is that right?

**Comment by mbroecheler** [comment]
One thing to throw out there: Somewhere in the 0.3.x line of Titan, the BerkeleyDB adapter had a bug where it would not close an iterator after going a g.V (or similar) which would cause an exception upon commit. Not sure you are using BDB here or whether this bug has anything to do with this. Just thought it worthwhile to point out. This has since been fixed.

@spmallette What can we do to get the full exception stack trace from Rexster or log it somewhere so that it is easier to debug these cases?

**Comment by spmallette** [comment]
You can always get more logs by running rexster with `-d` and by adding a custom `log4j.properties` file:

https://github.com/tinkerpop/rexster/wiki/Rexster-Configuration#logging-configuration 

Going to re-test with 0.4.0 as soon as I get past some problems with building the distribution.

**Comment by spmallette** [comment]
I can't recreate the problem using my repro steps under 0.4.0.  Closing, pending more information from original poster.
