### ISSUE TITLE
Multiquery performance test

### ISSUE THREAD

**Issue by mbroecheler** [thinkaurelius/titan#378]

**Comment by dalaro** [comment]
I added three test methods on GroovySerialTest in ca98a67eead60c5e0ee744968d6852b238fa9177 and fa7b9191b1ce1ce388abcb10cbe7e3014cf161aa.  Here's a summary.
- testMultiVertexQuery runs a sequence of 3 transactions, each for a set of 50 vertices.  Iterating over 10 edge labels one at a time, the tx multiQueries labeled edges incident on its 50 vertices.  Both here and below, the "magic" numbers are arbitrarily chosen and configurable.
- testPathologicalMultiVertexQuery is similar to the test above, except it only sets one vertex per multiQuery, increasing the total number of queries by 50x while holding the total number of vertices and labels iterated over constant.  It commits after every 50 vertices.  I intended "pathological" or "degenerate" in the sense that I'm defeating the point of multiQuery and using it like ordinary VertexCentricQuery just to see what happens.
- testSingleVertexQuery does essentially the same as PathologicalMulti, except using the ordinary VertexCentricQuery interface instead of multiQuery. It commits after every 50 vertices.

All three methods are implemented using a shared helper method in GroovyTestSupport, chunkedSequentialUidTask, which takes a vertex chunk size, vertices per tx and a closure as parameters.  A precondition forces vertices per tx to be divisible by vertex chunk size.

There should be almost no difference between PathologicalMulti and Single, though Single might have a slight edge.  Both should be noticeably slower than Multi on Cassandra or HBase.  Informal JUnitBenchmarks testing on my laptop with in-process Cassandra and the Thrift adapter showed these numbers:
- testMultiVertexQuery, 72 iterations (+1 warmup): time.bench=15.73s
- testPathologicalMultiVertexQuery, 5 iterations (+1 warmup): time.bench=8.68s
- testSingleVertexQuery, 5 iterations (+1 warmup): time.bench=7.95s

Adjusting for iteration count and runtime, Multi beats PathologicalMulti and Single by about 7.9x and 7.3x, respectively.  I think this fits reasonably well with expectations.
