### ISSUE TITLE
Feature request: Support for disabling Snappy compression Cassandra

### ISSUE THREAD

**Issue by freakinruben** [thinkaurelius/titan#379]
I would like to have the possibility to disable snappy-compression when using Cassandra. Disabling snappy in Cassandra right now means that I can't use Titan, so it would be nice to have this as a Cassandra specific configuration option.

**Comment by xedin** [comment]
I will make it an option in the configuration, meanwhile you can just set "compressionOptions" to "null" for all CFs in titan keyspace using CLI that would disable compression for new data, compaction would also decompress old data.

**Comment by xedin** [comment]
@freakinruben as compression is done on schema level, what behavior are you looking for? I guess that option should only be taken into account the every first time you open the graph and everything initialize, otherwise we are risking to create schema disagreements if we are going to try switch it off/on every time graph is open. Can you also elaborate how you tried to disable compression and why you couldn't use Titan after that? Compression on Cassandra level should be completely transparent to Titan so if you change schema in Cassandra to disable it that shouldn't affect Titan operation at all.

@mbroecheler WDYT about first question?

**Comment by mbroecheler** [comment]
@xedin I agree, this configuration option should only have any affect when Titan first initializes. Subsequent changes in compression need to be done via the cli and not the configuration option.

**Comment by xedin** [comment]
@mbroecheler Pull request at https://github.com/thinkaurelius/titan/pull/397
