### ISSUE TITLE
Classpath issue with titan-cassandra-0.3.2

### ISSUE THREAD

**Issue by mpouttuclarke** [thinkaurelius/titan#381]
When I run gremlin:
gremlin> g = TitanFactory.open('bin/cassy-lucy.local')

I get the following:
2835 [main] INFO  com.thinkaurelius.titan.diskstorage.Backend  - Configuring index [search] based on: 
 backend: lucene
directory: /data/01/lucene/titan

Could not find implementation class: com.thinkaurelius.titan.diskstorage.lucene.LuceneIndex

$ cat bin/cassy-lucy.local 
storage.backend=embeddedcassandra

storage.index.search.backend=lucene
storage.index.search.directory=/data/01/lucene/titan

**Comment by dkuppitz** [comment]
There's no LuceneIndex. You're probably looking for:

```
storage.index.search.backend=elasticsearch
```

See [Using Elastic Search](https://github.com/thinkaurelius/titan/wiki/Using-Elastic-Search) for more details.

**Comment by mpouttuclarke** [comment]
```
    Configuration storage = config
            .subset(GraphDatabaseConfiguration.STORAGE_NAMESPACE);
    storage.setProperty(GraphDatabaseConfiguration.STORAGE_BACKEND_KEY,
            "embeddedcassandra");
    storage.setProperty("cassandra-config-dir", String
            .format("file://%s", new File(
                    "src/test/resources/cassandra.yaml").getAbsolutePath()));
    storage.setProperty("index.search.backend", "lucene");
    storage.setProperty("index.search.directory", "target/titan/lucene");
```

Seems to work fine from java :)

**Comment by mpouttuclarke** [comment]
https://github.com/thinkaurelius/titan/wiki/Using-Lucene

^^

**Comment by mpouttuclarke** [comment]
```
    <dependency>
        <groupId>com.thinkaurelius.titan</groupId>
        <artifactId>titan-core</artifactId>
        <version>0.3.2</version>
    </dependency>
    <dependency>
        <groupId>com.thinkaurelius.titan</groupId>
        <artifactId>titan-cassandra</artifactId>
        <version>0.3.2</version>
    </dependency>
    <dependency>
        <groupId>com.thinkaurelius.titan</groupId>
        <artifactId>titan-lucene</artifactId>
        <version>0.3.2</version>
    </dependency>
```

**Comment by dalaro** [comment]
I confirmed this with titan-cassandra-0.3.2.zip.  The -all zip has a titan-lucene jar, but the -cassandra zip does not.  I think the HBase (and BDB?) distros are the same.  I'll  add these dependencies to the titan-dist-cassandra (and -hbase, -bdb) pom.xml files under the release profile.

None of this affects using Titan through Maven.  This problem is specific to the distribution zipfiles.

As a workaround for right now, you could use the titan-all-0.3.2.zip, which contains everything.

**Comment by mpouttuclarke** [comment]
Thanks!  Having fun with Titan but just wanted to make sure no one hit this snag :)

**Comment by dkuppitz** [comment]
Ha, sorry for that, never recognized the Lucene implementation :).

**Comment by dalaro** [comment]
I played with the BDB assembly descriptor.  Compared to just distributing the BDB backend, Titan core, and associated dependencies, dding Lucene increases the size 11%.  Adding Lucene + ES increases it 44%.  There are no real savings in shipping just ES but not Lucene, since ES depends on most of Lucene.

I updated the [Downloads](https://github.com/thinkaurelius/titan/wiki/Downloads) wiki page to explain what's in each of the 0.3.2 backend-specific distros: the backend adapter plus ES.

For 0.4.X, I'm leaning towards making the backend-specific distros as small as possible by shipping just the backend adapter, core, and required deps.  No indexing backends or cache stores.

I also had a fever dream about using some kind of partial maven embedding to acquire Titan component jars and all their transitive dependencies on-demand at runtime, modifying live classloaders to include these new jars as they are downloaded, embracing 3rd-party indexing and storage adapters as well as the standard Titan ones through new configuration keys.  I looked a little bit and found https://github.com/smreed/dropship.  I am concerned about whatever bizarre failure modes could emerge from network failures, inability to write jars to the filesystem, or unconventional classloader configurations.  It's probably not worth the complexity right now.
