### ISSUE TITLE
Run Titan on Windows as a Windows Service? 

### ISSUE THREAD

**Issue by kevinschumacher** [thinkaurelius/titan#392]
When running Titan on Windows, it would be helpful to be able to run the program in the background as a Windows Service. This has advantages such as:
-  Automatically starting when the server boots
-  Not having a console window running on a logged in user's session
-  Graceful shutdown when the system shuts down (as opposed to Windows just killing the process as I believe happens if the system is shut down with user sessions open)

Is that possible with the current releases of Titan?

**Comment by spmallette** [comment]
There was a time when someone contributed a wiki page to Rexster that explained how to get Rexster running as a windows service.  I've long since removed that page as the original submitter no longer wished to maintain it.  In any case, here is the page from the Rexster wiki archives:

http://www.tinkerpop.com/docs/wikidocs/rexster/2.0.0/Wrapping-as-a-Windows-Service.html

Perhaps it can help you find a way to make Titan/Cassandra/Rexster work nicely for you.  As far as specific and direct support for running Titan in that fashion, i'll have to leave that to @dalaro or @mbroecheler to say what Titan will/won't do in the future.

**Comment by spmallette** [comment]
Given that we haven't seen any action on this since it was first discussed, I'm going to assume that this is not something Titan will support out of the box.  The "rexster wrapping" i referenced in the link above btw ended up being a hassle to manage as i recall - probably not something we'd want in the picture anyway.
