### ISSUE TITLE
Metrics coverage for TitanTransaction

### ISSUE THREAD

**Issue by mbroecheler** [thinkaurelius/titan#402]
Metrics coverage for transaction    
- get coverage of transaction time, count, failures (by type: locking vs persistence vs other) => wrapper around TitanTx (MetricInstrumentedTransaction)
- vertex retrieval by id (counts) in MetricInstrumentedTransaction (wrapping method)
- VertexQuery, GraphQuery (counts, times) in QueryExecutor

**Comment by dalaro** [comment]
1e0a628 is a QueryExecutor wrapper that measures time spent in and call/exception counts on all of the interface methods.  The graph and vertex query executors are separately wrapped when metrics are enabled.  These metrics appear by default in the namespaces com.thinkaurelius.titan.query.{graph,vertex}.*, though they honor a transaction-specific metrics name prefix if one is set.  The wrapper doesn't measure time spent calling methods on iterators returned from QueryExecutor methods.

getVertex(long) counter: ef5a13638aee552501c7cc76a03f382b12f8a221

Counters on attempted & failed lock write, check, and delete attempts in AbstractLocker (which ConsistentKeyLocker inherits): b32822c8078b62fb9a8b0826d4591e131af71ee0

b8258e12952c8201327c0a78893319dac0ede63b is a Metrics configuration cleanup.  I let Metrics config option handling get way too chaotic.  For instance, GraphDatabaseConfiguration checked metrics.enable-basic-metrics, but Backend checked storage.enable-basic-metrics.  There's no compelling reason for these options to be separate, and they're not documented as separate.  I added helper method that checks these two options and "metrics.enabled" and considers Metrics globally active if any one of them is true.  I also made a mirror-image change for metrics.merge-basic-metrics and storage.merge-basic-metrics.  This commit should not disable anybody's metrics, though it will enable additional metrics in a config that previously only had a partial set of Titan's metrics activated.

I haven't created a MetricInstrumentedTransaction yet.  Unlike other MetricInstrumented*, StandardTitanTx is a concrete class instead of an interface, so it's possible to make changes without deepening our ever-growing stacktraces.  We certainly could refactor all of StandardTitanTx's changes into a wrapper class, but I had already started tx commit/abort/begin counts inline rather than in a wrapper, so I continued with that for 0.4.2 instead of overhauling it.
