### ISSUE TITLE
Faunus SLF4J issues with Titan 0.4.0-SNAPSHOT

### ISSUE THREAD

**Issue by okram** [thinkaurelius/titan#412]
I had this problem earlier in Faunus and was able to use Apache Logger to get around it. But this is in Titan's code and Faunus can't read graphs (HBase or Cassandra).

_HBASE_

```
gremlin> g = FaunusFactory.open('bin/titan-hbase-input.properties')
==>faunusgraph[titanhbaseinputformat->graphsonoutputformat]
gremlin> g.V.map
09:21:36 WARN mapreduce.FaunusCompiler: Using the developer Faunus job jar: target/faunus-0.4.0-SNAPSHOT-job.jar
09:21:36 INFO mapreduce.FaunusCompiler: Compiled to 1 MapReduce job(s)
09:21:36 INFO mapreduce.FaunusCompiler: Executing job 1 out of 1: MapSequence[com.thinkaurelius.faunus.mapreduce.transform.VerticesMap.Map, com.thinkaurelius.faunus.mapreduce.transform.PropertyMapMap.Map]
09:21:36 INFO mapreduce.FaunusCompiler: Job data location: output/job-0
09:21:36 WARN mapred.JobClient: Use GenericOptionsParser for parsing the arguments. Applications should implement Tool for the same.
SLF4J: slf4j-api 1.6.x (or later) is incompatible with this binding.
SLF4J: Your binding is version 1.5.5 or earlier.
SLF4J: Upgrade your binding to version 1.6.x.
09:21:37 INFO mapred.JobClient: Cleaning up the staging area hdfs://localhost:9000/tmp/hadoop-marko/mapred/staging/marko/.staging/job_201310080859_0005
org.slf4j.impl.StaticLoggerBinder.getSingleton()Lorg/slf4j/impl/StaticLoggerBinder;
Display stack trace? [yN] y
java.lang.NoSuchMethodError: org.slf4j.impl.StaticLoggerBinder.getSingleton()Lorg/slf4j/impl/StaticLoggerBinder;
    at org.slf4j.LoggerFactory.bind(LoggerFactory.java:128)
    at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:107)
    at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:295)
    at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:269)
    at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:281)
    at com.thinkaurelius.titan.graphdb.blueprints.TitanBlueprintsGraph.<clinit>(TitanBlueprintsGraph.java:24)
    at com.thinkaurelius.faunus.formats.titan.hbase.TitanHBaseInputFormat.setConf(TitanHBaseInputFormat.java:53)
```

_CASSANDRA_

```
Caused by: java.lang.IllegalStateException: org.slf4j.LoggerFactory could not be successfully initialized. See also http://www.slf4j.org/codes.html#unsuccessfulInit
    at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:303)
    at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:269)
    at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:281)
    at org.apache.cassandra.hadoop.ColumnFamilyInputFormat.<clinit>(ColumnFamilyInputFormat.java:71)
    ... 78 more
```

**Comment by okram** [comment]
The problem is that titan-core and titan-hbase have two different versions of SLF4J. A simple exclusion in Faunus on titan-hbase fixes the problem above: https://github.com/thinkaurelius/faunus/blob/master/pom.xml#L97 ...

**Comment by dalaro** [comment]
This aroused my curiosity, since Titan's maven-enforcer-plugin configuration is supposed to prevent problems like this one.

#280 makes log4j and its slf4j binding optional dependencies.  The objective was to allow Titan users to choose their own logging backend (e.g. logback instead of log4j).  Titan's maven artifacts now depend only on slf4j-api and not on log4j or slf4j-log4j12 unless the user requests them by declaring them in the client app's pom.  I should document this in the wiki for 0.4.0.

Here are the versions of logging jars resolved by Faunus prior to your exclusions in titan-hbase:

```
faunus$ ls -1 target/faunus-0.4.0-SNAPSHOT-standalone/lib/{slf4j,log4j}*
target/faunus-0.4.0-SNAPSHOT-standalone/lib/log4j-1.2.16.jar
target/faunus-0.4.0-SNAPSHOT-standalone/lib/slf4j-api-1.7.5.jar
target/faunus-0.4.0-SNAPSHOT-standalone/lib/slf4j-log4j12-1.4.3.jar
```

I just discovered that HBase is special when it comes to logging:
- https://issues.apache.org/jira/browse/HBASE-2608
- http://hbase.apache.org/book/config.files.html#client_dependencies

Nutshell version: HBase depends on log4j, commons-logging, and slf4j.  A migration from commons-logging to slf4j has started, but is seemingly stalled since 2010.  titan-hbase depends on the hbase artifact, which in turn depends on slf4j-log4j12-1.4.3 and log4j-1.2.16.  The enforcer plugin seems to give precedence to the optional dependencies in Titan's top-level pom.xml vs HBase's dependencies, but Maven seems to do it the other way around in Faunus at runtime.  Maybe there's a way to configure enforcer to consider the Faunus scenario, which seems a pretty likely use case.

I modified titan-hbase's pom.xml to declare hard dependencies on log4j and slf4j-log4j12 at their Titan-wide versions.  This is not completely optimal, but it makes far more sense then allowing Titan's slf4j-api version (1.7.5) alongside the HBase client's ancient slf4j-log4j12 version (1.4.3).

Here are the versions with your exclusions in titan-hbase (note slight mismatch between slf4j-api and log4j binding):

```
faunus$ ls -1 target/faunus-0.4.0-SNAPSHOT-standalone/lib/{slf4j,log4j}*
target/faunus-0.4.0-SNAPSHOT-standalone/lib/log4j-1.2.16.jar
target/faunus-0.4.0-SNAPSHOT-standalone/lib/slf4j-api-1.7.5.jar
target/faunus-0.4.0-SNAPSHOT-standalone/lib/slf4j-log4j12-1.7.2.jar
```

Here are the versions after deploying a new titan-hbase snapshot and removing your exclusions from titan-hbase:

```
faunus$ ls -1 target/faunus-0.4.0-SNAPSHOT-standalone/lib/{slf4j,log4j}*
target/faunus-0.4.0-SNAPSHOT-standalone/lib/log4j-1.2.17.jar
target/faunus-0.4.0-SNAPSHOT-standalone/lib/slf4j-api-1.7.5.jar
target/faunus-0.4.0-SNAPSHOT-standalone/lib/slf4j-log4j12-1.7.5.jar
```

I modified Faunus's pom in https://github.com/thinkaurelius/faunus/commit/c98f7ed24429379b28a5fc38d33d8149af1bbf99 and https://github.com/thinkaurelius/faunus/commit/4913f588b966cf4249a972d4893bb4198255b519 to make it a little more resistant to logging dependency version problems in the future.
- I added a log4j dependency to Faunus's pom.  Faunus logs through org.apache.log4j.  Its pom didn't declare a direct dependency on log4j.  Faunus gets log4j transitively through other dependencies, but that approach leaves the log4j version at the mercy of the other projects.  So I added an explicit log4j dependency Faunus's pom.xml to prevent the log4j version from floating.
- I added a dependencyManagement section that will keep Faunus's slf4j and slf4j-log4j12 versions in agreement regardless of what happens in titan-hbase or other dependencies.
