### ISSUE TITLE
[Titan04/SNAPSHOT] Be nice to have titan-cassandra-?local?.properties

### ISSUE THREAD

**Issue by okram** [thinkaurelius/titan#418]
We no longer seem to have cassandra.local and hbase.local in conf/ anymore.

**Comment by dalaro** [comment]
You're right, we should keep those.

hbase.local was just renamed.  The contents of conf/titan-hbase.properties are the same as the old hbase.local.

But cassandra.local had no equivalent in conf.  I just restored the contents of cassandra.local to conf/titan-cassandra.properties.  This connects to 127.0.0.1 using the cassandrathrift adapter.  I renamed the embedded & embedded+es configs to titan-cassandra-embedded(-es).properties.  I think this renaming is appropriate since embedded is going unsupported -- the default "titan-cassandra.properties" file should not use the embedded adapter.
