### ISSUE TITLE
Too much INFO/WARN with Hazelcast in Gremlin REPL

### ISSUE THREAD

**Issue by okram** [thinkaurelius/titan#424]
Please play with Hazelcast in the Gremlin console. There is an excess amount of INFO information that makes using the REPL a bad experience.

In general, please test all the databases in the REPL and note the experience you have. Many problems can be realized about the set up ( ../db, INFOs, etc.)

**Comment by okram** [comment]
Not so bad once you get past the initial TitanFactory.open() and the first few commands.

**Comment by dalaro** [comment]
I like all those messages on startup, but you're right that it's hideous for the general-case user experience.  I've turned the threshold up to WARN (1dc2bc8a7bc28209d080b69b3b1d4803cf06efd6).

By the way, I created a `conf/log4j.properties` file in the distros (and the repo root) that takes precedence over any packed in the jars.  This makes it modifying logging settings slightly less annoying because it's just a file edit and REPL restart.
