### ISSUE TITLE
Old wikidoc HTMLs have all their images as broken links

### ISSUE THREAD

**Issue by okram** [thinkaurelius/titan#432]
http://thinkaurelius.github.io/titan/wikidoc/0.3.0/Home.html

Both in titan and faunus.

**Comment by dalaro** [comment]
The wikidoc generated for versions 0.3.1 and earlier contained absolute URLs pointing to the Github master.  Master has changed since then.  0.3.2's generated wikidoc was not affected because I moved all the image links into the wiki repository and made the URLs relative, protecting it from future changes in master.

I gave each of the wikidoc folders for 0.3.1 and earlier an images subdirectory and ran sed replacements from each of the affected wikidoc/$VERSION folders:

``` bash
# For Titan -- changed "titan" to "faunus" for Faunus
for h in *.html; do
    sed -ri \
     's|https://github.com/thinkaurelius/titan/raw/master/doc/images/|images/|g;
      s|https://raw.github.com/thinkaurelius/titan/master/doc/images/|images/|g' \
     $h;
done
```

Commits:
- thinkaurelius/titan@e8197fc5087293775f7f8db5c7c35bc9a05c342a
- thinkaurelius/faunus@78144a3789f13b9d02f2b8b6987fcc4d6f8bdda1
