### ISSUE TITLE
Use same timestamp method in Hbase as in Cassandra

### ISSUE THREAD

**Issue by mbroecheler** [thinkaurelius/titan#472]
1) see TODO on line 164: uncomment 2 following lines, remove lines 168-170
2) do we still need waitUntil(putTS) since the difference is now just one ns?

**Comment by dalaro** [comment]
1. Implemented as part of #483.  I also updated the delete command timestamps in `clearStorage`.
2. I think we only need waitUntil(putTS) at millisecond resolution.  When I ran the Cassandra test suite with millisecond timestamps, it died with unusual test failures that seemed to be due to overlapping writes with the same timestamps (that don't occur with nanosecond resolution).
