### ISSUE TITLE
Make a backwards compatible test case.

### ISSUE THREAD

**Issue by okram** [thinkaurelius/titan#473]
Make a test case that generates a graph using Titan x.y.z our of Central Repo and then ensure that x.y.z+1-SNAPSHOT can property interact with it.

**Comment by mbroecheler** [comment]
Yeah, I was thinking about that. How does one make such a test case though?
That would somehow require multiple class loaders to keep different
versions of Titan around.

If anybody has an idea on how to implement this elegantly, please let me
know. We definitely need this.

On Sat, Nov 9, 2013 at 5:23 PM, Marko A. Rodriguez <notifications@github.com

> wrote:
> 
> Make a test case that generates a graph using Titan x.y.z our of Central
> Repo and then ensure that x.y.z+1-SNAPSHOT can property interact with it.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/thinkaurelius/titan/issues/473
> .

## 

Matthias Broecheler
http://www.matthiasb.com

**Comment by okram** [comment]
You can do as simple as if the version is x.y.0, generate a mini-database for each backend and tar -xf up the folder. Then if the verison is x.y.z (z != 0), untarball the folder and run queries against it to make sure no exceptions and correct results are returned. Some pom magic will have to come in here.

**Comment by dalaro** [comment]
I've implemented a basic compatibility test on titan05 in e30beedaebff1fd6af47449c3b5b2ad31784a78a.  This only applies to 0.5.x and later.

To summarize that commit message: each 0.5.x and later release is assumed to be compatible with every prior release up to 0.5.0.  GotG is automatically loaded into each 0.5.0+ version of Titan/BDB+ES during release.  The resulting files are archived and uploaded to S3.  Every release downloads each prior release's archive one at a time, extracts it, and opens it and runs some queries that attempt to exercise basic reads, including mixed, composite, and edge indices.  I manually generated the archive for 0.5.0 so that 0.5.1 can test against it.  I ran simulated local releases of 0.5.1 and 0.5.2 to test it.

I also streamlined the release process a bit, pulling several steps into a single helper script (and updated RELEASING.md accordingly).

A few salient points:
- The test archives are publicly readable.  Although they're stored in S3, the test harness just works with HTTP URLs.  It's possible to run the compat tests without access to our S3 bucket.
- The list of compatible prior releases is completely decoupled from `titan.compatible.versions`.  This test assumes DBs created by every prior release back to 0.5.0 should be readable, and it fails if the releaser fails to update `titan.compatible.versions`.  I made it this way specifically to avoid a repeat of 0.4.3.
- The streamlined release.sh script displays the current titan.compatible.versions and asks the releaser if he would like to append to it, which should make that step harder to forget.
