### ISSUE TITLE
Problem with using TitanGraph with more than one thread

### ISSUE THREAD

**Issue by SakulK** [thinkaurelius/titan#51]
Hi,
I'm getting an exception from TitanGraph when I use something like this:

``` Java
TitanGraph graph = TitanFactory.open(GRAPH_PATH);
graph.createKeyIndex("name", Vertex.class); 

graph.getVertices("name", name).iterator() // in another thread
```

the Exception is

```
Exception in thread "Thread-1" java.lang.UnsupportedOperationException: getVertices only supports indexed keys since TitanGraph does not support vertex iteration outside the transaction
    at com.thinkaurelius.titan.graphdb.transaction.AbstractTitanTx.getVertices(AbstractTitanTx.java:467)
    at com.thinkaurelius.titan.graphdb.transaction.AbstractTitanTx.getVertices(AbstractTitanTx.java:443)
    at com.thinkaurelius.titan.graphdb.blueprints.TitanBlueprintsGraph.getVertices(TitanBlueprintsGraph.java:137)
```

it works fine when using TitanGraph in just one thread but I dont really understand why it works that way. Am I missing something or is it a bug?

Cheers

**Comment by SakulK** [comment]
It works fine with the InMemory version of TitanGraph

**Comment by DanielThomas** [comment]
Try this on the first thread:

```
graph.stopTransaction(Conclusion.SUCCESS)
```

**Comment by mbroecheler** [comment]
As Danny pointed out, if you do

``` java
TitanGraph graph = TitanFactory.open(GRAPH_PATH);
graph.createKeyIndex("name", Vertex.class); 
graph.stopTransaction(Conclusion.SUCCESS);

graph.getVertices("name", name).iterator() // in another thread
```

it should work. Here is the reason:
In Blueprints, each thread automatically opens its own transaction. So, the createKeyIndex call is in one transaction and the getVertices call is in another. Since the first transaction has not been stopped/committed the other transaction cannot see its results - consequently you get the error.
If you would like to use the same transaction in both threads, call startTransaction on the graph which returns a transaction handle that is detached from the thread context.

**Comment by SakulK** [comment]
Thank you, that helped alot :)
