### ISSUE TITLE
Why are you shipping out titan-all-0.4.1? Isn't it supposed to be titan-server-0.4.1?

### ISSUE THREAD

**Issue by haebin** [thinkaurelius/titan#514]
titan-all-0.4.1.zip is somewhat useless.
I don't know how to use it since it does not have any proper scripts to run titan server.

Isn't is supposed to be titan-server-0.4.1.zip?

I always download titan source and build it myself to get the zip.
(Is it only me?)

Please check the distribution package.
Thank you.

**Comment by mbroecheler** [comment]
Yeah, we are also realizing that our distributions are somewhat
unfortunate. We wanted to provide a distribution that does not include
Rexster and all its dependencies for those who don't need it (given the
amount of extra stuff that this pulls in) but the name "all" is confusing.

We will rework our distribution management for the next release.

On Wed, Dec 4, 2013 at 6:09 PM, Frederick Haebin Na <
notifications@github.com> wrote:

> titan-all-0.4.1.zip is somewhat useless.
> I don't know how to use it since it does not have any proper scripts to
> run titan server.
> 
> Isn't is supposed to be titan-server-0.4.1.zip?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/thinkaurelius/titan/issues/514
> .

## 

Matthias Broecheler
http://www.matthiasb.com

**Comment by haebin** [comment]
Thank you, Matthias. :D

**Comment by dalaro** [comment]
Somewhat unfortunate was an understatement.  But we've done some early spring cleaning:  c71ef578aac27f074fa8600e276258c4d57b40c6

I deleted all of the `titan-dist-*` modules and retained only a singe `titan-dist` module.  This produces one zipfile/tarball, `titan-$VERSION.zip/.tar.bz2`.  Its contents are the contents of the old titan-server distros.

Combining poms, reshuffling assembly descriptors, deleting modules, and aggregating integration tests provides a lot opportunities for me to miss something.  Here are the things I checked:
- contents of bin/, lib/, conf/ still generated in the repo root when building titan (so-called "standalone" or "filesystem" assembly descriptor)
- expect-based distro integration tests all combined under titan-dist instead of spread across now-deleted modules
- .deb controlfiles and .rpm specfile still generate correctly from titan-dist with -Ppkg-tools, though they are out-of-date since the removal of RexsterTitanServer

We'll update the downloads page and remove the feature matrix when 0.5 is released.
