### ISSUE TITLE
Improve titan.sh script

### ISSUE THREAD

**Issue by mbroecheler** [thinkaurelius/titan#538]
Change 1: (jps was not available at /usr/bin as I installed sun jdk using tar)
local p=`${JAVA_HOME}/bin/jps -l | grep "$2" | awk '{print $1}'`

Change 2: (solution to the exception at the beginning of this thread)
stop() {
    kill_class 'Titan + Rexster' com.tinkerpop.rexster.Application 
    sleep 60
    kill_class Cassandra org.apache.cassandra.service.CassandraDaemon
}

**Comment by dalaro** [comment]
Regarding Change 2.  Hardcoded sleep times in titan.sh that mask racy operations will inevitably cause problems (for past experience, see first bullet in #463).

The suggestion comes from [an aureliusgraphs posting](https://groups.google.com/d/msg/aureliusgraphs/bviB6E5TZ-A/-ASMm_AYppQJ) where the context explains that a sleep was necessary to let Rexster complete graph shutdown before killing Cassandra.  Instead of relying on a hardcoded sleep interval, I took a similar approach as in #463.  After sending a signal to Rexster, titan.sh will wait up to 60 seconds by default (or whatever the value of the environment variable `$REXSTER_SHUTDOWN_TIMEOUT_S`) for the process to disappear from the process table.  Only after Rexster dies or exceeds the timeout does titan.sh attempt to kill Cassandra.
