### ISSUE TITLE
Unrecognized VM option 'UseCondCardMark'  problem and solution

### ISSUE THREAD

**Issue by hzlijianjun** [thinkaurelius/titan#548]
Error at launching by: bin/titan.sh -c cassandra-es start
Unrecognized VM option 'UseCondCardMark'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

My env:
OS:  Linux version 2.6.32-220.el6.i686 (mockbuild@c6b18n3.bsys.dev.centos.org) (gcc version 4.4.6 20110731 (Red Hat 4.4.6-3) (GCC) ) #1 SMP Tue Dec 6 16:15:40 GMT 2011
TITAN: titan-server-0.4.0

Solution:  add -server to JVM_OPTS in conf/cassandra-env.sh
relattive infomation : http://docs.oracle.com/javase/7/docs/technotes/guides/vm/

**Comment by hzlijianjun** [comment]
This problem occurs in  titan-server-0.4.1 too. that same solution for it.

**Comment by dalaro** [comment]
The only grep hit for UseCondCardMark in the titan repo is cassandra-env.sh (and the currently unused titan-env.sh).

Cassandra already encountered and fixed it: https://issues.apache.org/jira/browse/CASSANDRA-6190.  Rather than adding `-server`, they omit UseCondCardMark on 32-bit.

This bug only affects 32-bit Oracle 7 VMs, since only server mode is available on 64-bit Oracle 7 (`-client` is accepted but silently ignored).

**Comment by dalaro** [comment]
I reapplied the patch from CASSANDRA-6190 on our copy of cassandra-env.sh (and titan-env.sh).
