### ISSUE TITLE
If possible, depend on Hadoop 1.0.3 (hadoop-core)

### ISSUE THREAD

**Issue by okram** [thinkaurelius/titan#55]
This way its the same dependency for Faunus.

**Comment by mbroecheler** [comment]
Dan, can we go to hadoop 1.0.3 or does this require updating hbase as well?

**Comment by dalaro** [comment]
I looked at the poms involved.  HBase 0.92.1 depends on hadoop-core 1.0.0 and therefore would probably but not necessarily work with hadoop-core 1.0.3.  Fortunately, I don't think we have to find out, because HBase 0.94.1 is now on Maven Central and depends it on hadoop-core 1.0.3.  I updated my local pom and the HBase tests in the comprehensive profile passed.  I pushed these pom changes bringing us to hadoop-core 1.0.3 and hbase 0.94.1 onto titan0.1.
