### ISSUE TITLE
HBaseStoreManager overrides default HBase properties

### ISSUE THREAD

**Issue by shaie** [thinkaurelius/titan#559]
According to what I read on https://github.com/thinkaurelius/titan/wiki/Using-HBase, we should specify storage.hbase-config only if we wish to override or explicitly set some hbase properties. My HBase cluster configuration specifies "hbase.zookeeper.quorum" and "hbase.zookeeper.property.clientPort" specifically (in hbase-site.xml), yet I noticed that if I don't include "storage.hbase-config.*" in my Titan configuration, they are not taken into account, and rather are set to:
- hbase.zookeeper.quorum=node1, where node1 is one of the nodes specified under storage.hostname
- hbase.zookeeper.property.clientPort=9000, where 9000 is set as storage.port.

That's a problem since I setup my zookeeper client port to 2181 (which is actually the default) and my hbase server to list on 9000.

After digging in the code, I found that HBaseStoreManager ctor sets these two properties to whatever is defined as "storage.port" and "storage.hostname":

```
this.hconf = HBaseConfiguration.create();
for (Map.Entry<String, String> confEntry : HBASE_CONFIGURATION.entrySet()) {
  if (config.containsKey(confEntry.getKey())) {
    hconf.set(confEntry.getValue(), config.getString(confEntry.getKey()));
  }
}
```

I think this is wrong, or I misunderstand the writeup on the Wiki page. What follows this code immediately is this:

```
// Copy a subset of our commons config into a Hadoop config
org.apache.commons.configuration.Configuration hbCommons = config.subset(HBASE_CONFIGURATION_NAMESPACE);
```

This seems the right thing to do - if someone wants to override his HBase settings, he should set storage.hbase-config.*, but otherwise, I don't think Titan should override the default settings on its own.

If this isn't a bug, then the writeup on the Wiki page should change, because currently, if your ZK clientPort != HBase port, you cannot open a connection to graph.

I think, maybe, the difference is when you run ZK outside of HBase (as in my case) vs if you run HBase and it itself spawns the ZK instance. Perhaps in this case the HBase and ZK ports are the same, but in general I think Titan shouldn't touch these props by default, and leave it to the user to specify storge.hbase-config.\* if he wishes to.

**Comment by shaie** [comment]
Actually, I think it's wrong that Titan sets these properties to any value itself. For instance, if my cluster has 3 machines: hb1, hb2 and zk1 -- One ZK server, two HBase servers, ZK is external to HBase, then it doesn't even make sense for Titan to set the zookeeper.quorum to storage.host (which will be the HBase servers).

So I'm now more convinced that Titan should only pass through storage.hbase-config.\* to hconf and not attempt to set any defaults.

**Comment by dalaro** [comment]
Here's how I understood the problem.  Please correct me if I've misunderstood your point.
1. The configuration key storage.port is confusing in the context of HBase, since clients may care about multiple ports (e.g. regionserver & ZK).
2. The wiki documentation for storage.port under HBase is vague and misleading.  It reads "port on which to connect to HBase cluster nodes." That's ambiguous, but it sounds more like the regionserver port than the ZK port; as implemented, the option controls the ZK port.

I've modified HBaseStoreManager in titan05 to ignore values of storage.hostname and storage.port.  Setting these in HBase logs warnings directing the user to equivalent quorum and port settings in hbase-site.xml or HBase config keys nested in the storage.hbase-config namespace.

The HBase adapter now uses only the following sources of configuration settings, listed in ascending order of precedence:
- hbase-default.xml (automatically loaded by `HBaseConfiguration.create()`)
- hbase-site.xml (also automatically loaded by `HBaseConfiguration.create()`)
- titan.hbase-config.*

**Comment by shaie** [comment]
In order to fix the problem, I think that the code doesn't need to explicitly set hbase.zookeeper.quorum and hbase.zookeeper.property.clientPort. If one wishes to control HBase setting through Titan config, he should set titan.hbase-config.*.

I think that letting one specify storage.hostname and storage.port is still important, e.g. in the absense of hbase-default/site.xml. For example, consider I run Titan on node-t and the HBase cluster is run on hb1 and hb2. I don't have hbase-site.xml on node-t, and it would seem awkward if I did, since I don't attempt to control HBase from that node (it is accessed by many other nodes). Rather, all Titan needs to know is the HBase hostname(s) and port. I don't think Titan needs to know the ZK host/port that HBase connects to -- it's specified on the hbase cluster.

So if your change loads hbase-site.xml by default, but still lets me specify storage.hostname and storage.port, that's the best option I think.

**Comment by dalaro** [comment]
"I don't think Titan needs to know the ZK host/port that HBase connects to -- it's specified on the hbase cluster."  I don't get it.  storage.hostname used to list the ZK ensemble hostnames.

Also, if the ZK clientPort in Titan's config is incorrect, e.g.

```
# ZK server's listen port is 2181 (default), 7777 is intentionally wrong
storage.hbase-config.hbase.zookeeper.property.clientPort=7777
```

then Titan throws these exceptions on startup:

```
WARN  org.apache.zookeeper.ClientCnxn  - Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739)
        at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:350)
        at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1068)
```

Separate question.  I don't get this: "I think that the code doesn't need to explicitly set hbase.zookeeper.quorum and hbase.zookeeper.property.clientPort...  I think that letting one specify storage.hostname and storage.port is still important".  How are storage.hostname and storage.port going to work unless they set the values of hbase.zookeeper.quorum and hbase.zookeeper.property.clientPort?  Is there another way?

**Comment by dalaro** [comment]
I've been thinking about this.  Removing `storage.hostname` is going to be a major annoyance for HBase users upgrading to 0.5, and I'm not really convinced it's justified.  It's less clear to me that people are overriding the default ZK port, but hostname is a big one.

I'm considering keeping storage.hostname and storage.port, but maybe:
1. Logging messages containing the HBase configuration keys to which they correspond when they are set, instead of silently overwriting the values from hbase-default.xml and/or hbase-site.xml
2. Updating the wiki page to describe exactly which HBase configuration keys they control

**Comment by shaie** [comment]
Hi Dan,

I don't think we should remove storage.hostname and storage.port. These are
required, as far as I understand, so Titan knows how to connect to the
storage backend. What bothered me is that if I don't specify
storage.hbase-config.zookeeper.stuff, then Titan defaults the ZK host and
port to the storage.host/post, which as I detailed is wrong in case your
HBase is connected to an external ZK.

My assumption was that Titan only needs to know the HBase host/port (the
region servers actually) and that the ZK host/port is only needed by the
region servers instances, which is what I specify in my hbase-site.xml on
the region server boxes. If that's not the case, i.e. the HBase client that
Titan connects through requires the same ZK host/port as defined on the
HBase cluster, then we shouldn't remove those configuration options.

In that case, it would make sense to default to storage.host/port, but I'd
change the documentation on the Wiki to denote that if your HBase cluster
connects to an external ZK ensemble, you must set these two parameters in
the Titan config.

Shai

**Comment by dalaro** [comment]
Hi @shaie

You wrote, "My assumption was that Titan only needs to know the HBase host/port (the region servers actually) and that the ZK host/port is only needed by the region servers instances".  Chapter 17 of the HBase manual seems to contradict this: "[All participating nodes and clients need to be able to access the running ZooKeeper ensemble.](http://hbase.apache.org/book/zookeeper.html)"

I'm not an expert on HBase internals, but I think clients use ZK in conjunction with the .META. and -ROOT- catalog tables to locate regionservers dynamically.  HBase's fully-distributed mode docs mention the `regionservers` file that lists all of the region server hostnames, but I thought that's just used in an ssh loop when remotely starting/stopping the regionserver processes on each machine.  I could be wrong about the `regionservers` file though, since its purpose is not extensively documented and I never investigated the source to see how it's used.

Regionserver network coordinates do live in ZK though. For example, when I start `bin/hbase zkcli` and run `ls /hbase/rs`, I see:

```
[zk: localhost:2181(CONNECTED) 4] ls /hbase/rs
[localhost,56125,1398884904957
```

And according to `netstat`, my local HMaster process held port tcp/56125 at the time.

I don't understand what you're saying about configuring a static list of regionservers on the client side.  How would the client handle regionservers getting added for the first time or decommissioned out of the cluster?  I thought ZK and .META./-ROOT- existed to solve these problems.

Please reopen/open a new issue if you think we can make progress on this.  Thanks!
