### ISSUE TITLE
Document Geoshape in the wiki

### ISSUE THREAD

**Issue by erickt** [thinkaurelius/titan#573]
While there are a couple references to `Geoshape` in the wiki, there is no real documentation of how to use it, or the fact that arrays and strings can be converted into a geoshape. It would be nice if there was an explicit section in the [Type Definition](https://github.com/thinkaurelius/titan/wiki/Type-Definition-Overview) page that goes into details about it and the rest of the types that Titan supports.

**Comment by tyoc213** [comment]
Adding to fixes on wiki
- https://github.com/thinkaurelius/titan/wiki/Graph-Configuration#wiki-storage-configuration Doesn't include cassandrathrift (I don't know if because deprecated or it is missing in the list).
- https://github.com/thinkaurelius/titan/wiki/Using-Persistit first link is broken points to https://github.com/pdbeaman/persistit instead of https://github.com/pbeaman/persistit
- https://github.com/thinkaurelius/titan/wiki/Type-Definition-Overview#wiki-default-type-creation will be nice to see the java line at less to see the correct string
- https://github.com/thinkaurelius/titan/wiki/Type-Definition-Overview in  "See Graph Configuration for more information on how to define custom attribute data types and handlers" sends you to https://github.com/thinkaurelius/titan/wiki/Graph-Configuration and there it sends you at the bottom "Datatype and Attribute Serializer Configuration" that finally leads to https://github.com/thinkaurelius/titan/wiki/Datatype-and-Attribute-Serializer-Configuration (so there is a middle step that only redirects you again)
- HDFS is not linked correctly in http://thinkaurelius.github.io/faunus/ HDFS link points to http://hadoop.apache.org/hdfs which is now 404

I copy those from google group.
- In https://github.com/thinkaurelius/titan/wiki/Datatype-and-Attribute-Serializer-Configuration#wiki-custom-object-serialization  has moved from  https://code.google.com/p/kryo/  -> https://github.com/EsotericSoftware/kryo 

---

As an addition, I will like that also
- Explain a little about open, there is no specification I could see that explain if you can or can't open more than one, that explain the threads and how to use it. I mean coming from pools and databases it seems like a pool, but how is handled, "how I get a a connection from the pool and how I restore it?"... like I see it is more about have your own thread use the graph instance you get from open... but I think to a newcomer it is hard to see it.
- In examples and wiki it is used strings like "storage.hostname" and others instead of GraphDatabaseConfiguration.STORAGE_BACKEND_KEY (making it a little hard to know if to use "" or the final String).
- Also there are "old videos" that be sintaxis they are "obsolete" or don't work for some one new, there could be some "pointers" on old documentation like:

``` scala
// g.makeType().name("name").dataType(String.class).indexed().unique().funcitonal(),makePropertyKey()
graph.makeKey("name").dataType(classOf[String]).indexed(classOf[Vertex]).unique().make()
```
- Also because there is no "migrations" or versioning of the definition of the graph, there could be a place where there is a explanation on how to handle a multiple developer workflow... and also how does https://github.com/thinkaurelius/titan/wiki/Titan-Limitations#wiki-types-can-not-be-changed-once-created impact that workflow, also a little mention about `./titan.sh clean` perhaps for this?.
- And for example the point below that... https://github.com/thinkaurelius/titan/wiki/Titan-Limitations#wiki-accidental-type-creation you see they use the direct name... but how it is named in java, how do I use it if I wanted to not have a typo? which is the correct key on `GraphDatabaseConfiguration`.

:ok_hand: 

Also note: external links that point to an internal part of a wiki, seem to have changed from `Configuration#custom` to `Configuration#wiki-custom` it seem like that.

**Comment by BrynCooke** [comment]
@mbroecheler 
Am I correct in thinking the only mixed indexes support Geoshapes?
Just want to confirm as the docs imply that composite indexes will handle anything.
Also when trying to create a composite index for a Geoshape property no error is thrown (although nothing seems to be indexed).

**Comment by BrynCooke** [comment]
I've added some documentation about geoshapes. The rest of the comments seem outdated as they refer to the old wiki.

**Comment by mbroecheler** [comment]
@BrynCooke  Composite indexes support geoshapes but only for equality search which is arguable of little use. A composite index could answer the query "What vertices have this exact point location" but it cannot do any distance or shape based queries.
