### ISSUE TITLE
Is Cassandra 2.0 compatible with Titan 0.4.2?

### ISSUE THREAD

**Issue by yammelvin** [thinkaurelius/titan#603]
I have no problem connecting Titan 0.4.2 with Cassandra 2.0.4
But Cassandra 2.0.4 is not in the compatibility list of Titan 0.4.2
Is it possible to include full comprehensive tests for Titan / Cassandra 2.0.4 and
add Cassandra 2.0.4 to the compatibility list please?

Thanks.

**Comment by MartinSeeler** [comment]
We are using Titan with Cassandra 2.0.4 - 2.0.6 and there are no issues so far. Even with more complex queries.

Is there any reason for the 1.2 compatibility?

**Comment by dalaro** [comment]
Titan uses Cassandra's Thrift API (with the exception of the embeddedcassandra adapter, which calls into StorageProxy without Thrift). That's been stable since Cassandra 1.0.  In theory, the client and server versions can vary independently as long as they are both newer than 1.0.

This is a little sticky on the Astyanax backend though.  The latest Astyanax release uses client version 1.2.  When I attempt to run it against a 2.0 client, Astyanax fails to instantiate TSockets because it's trying to call a constructor with a signature that seems to have been removed.  The Astyanax guys are working on a CQL-based beta driver that's compatible with 2.0, but I'm not really clear on whether they plan to release an update for the Thrift backend; my guess is that they want to focus on CQL.

We want to investigate some potential CQL3-related data layout and query efficiency issues before moving off Thrift.

titan05 currently uses Cassandra 2.0 on the client side.  This required extensive changes to the embedded adapter but just a one-liner in the cassandrathrift backend.  Astyanax got dropped for the reason described above.

Given the compatibility issues just described, I doubt we'll backport Cassandra 2.0 client-side support to the 0.4 line, but in many cases this won't matter, because the 1.2 client can speak Thrift to a 2.0 cluster/server.  We are planning to support Cassandra 2.x client support in Titan 0.5.
