### ISSUE TITLE
Question about vertexCache

### ISSUE THREAD

**Issue by leleueri** [thinkaurelius/titan#628]
Hi,

I'm using titan 0.4.2 and I have performed some benchmarks.

The first benchmark used a disabled titan cache (cache.db-cache = false) and during the profiling, we saw that the "getType" method is often called and request a vertex.

So we activated the cache and obviously, the performance was better.

So here is my questions :
- why TitanTypes are stored in the same cache as other vertices ?
- Are there some side effects to have a dedicated cache (always on) for TitanType?

BR,
Eric

**Comment by mbroecheler** [comment]
Hi Eric,

yes, the types are cached in the same cache, but there is another type
specific cache in front of the data store. So, the performance difference
is due to the other accesses.

Best,
Matthias

On Wed, Apr 16, 2014 at 1:09 AM, Eric notifications@github.com wrote:

> Hi,
> 
> I'm using titan 0.4.2 and I have performed some benchmarks.
> 
> The first benchmark used a disabled titan cache (cache.db-cache = false)
> and during the profiling, we saw that the "getType" method is often called
> and request a vertex.
> 
> So we activated the cache and obviously, the performance was better.
> 
> So here is my questions :
> - why TitanTypes are stored in the same cache as other vertices ?
> - Are there some side effects to have a dedicated cache (always on)
>   for TitanType?
> 
> BR,
> Eric
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/thinkaurelius/titan/issues/628
> .

## 

Matthias Broecheler
http://www.matthiasb.com
