### ISSUE TITLE
Cassandra CQL KeyColumnValueStore to replace CassandraThriftKeyColumnValueStore

### ISSUE THREAD

**Issue by alexliu68** [thinkaurelius/titan#652]
Cassandra latest native protocol is faster than thrift protocol according to some of the testing result in https://issues.apache.org/jira/browse/CASSANDRA-4718. We can also take advantage of https://github.com/datastax/java-driver built-in pooling, load balancing, security and other features.

This may involve some API changes in KeyColumnValueStore, especially change to SQL like query

**Comment by mbroecheler** [comment]
Alex, we did our own internal benchmarking and found the thrift adapter to be significantly faster than  CQL mostly because thrift has better batch-updates and supports multi_get_slice which makes a big difference through multi-query.
If you use Titan's Astyanax adapter you get pooling and load balancing. Titan also supports Cassandra security.
We will keep an eye on the CQL and java driver development but for now it would slow things down.

**Comment by alexliu68** [comment]
The latest Astyanax has  integrated Java-Driver. The following link show the details.
http://techblog.netflix.com/2013/12/astyanax-update.html

Do you have any benchmarking between AstyanaxStoreManager and CassandraThriftStoreManager? In which case, Astyanax is used? I find that by default setting, AstyanaxStoreManager is used instead of CassandraThriftStoreManager, is there any particular reason?

**Comment by mbroecheler** [comment]
The java driver does not (yet) support some of the operations we need for fast traversal execution. Our Astyanax and thrift adapters both you thrift under the hood, but astyanax adds automatic fail-over, ring detection and all these other nice properties. Hence, we recommend astyanax by default and thrift if you are running Titan and Cassandra co-local.
