### ISSUE TITLE
PartitionKeyIndexableGraph

### ISSUE THREAD

**Issue by kbrumer** [thinkaurelius/titan#676]
I would like to use both a PartitionGraph and a SailRepository. SailRepository requires a GraphSail which needs a KeyIndexableGraph. There is a PartitionIndexableGraph but no PartitionKeyIndexableGraph. 

Is this relatively straightforward? 

Thanks.

**Comment by spmallette** [comment]
This is really more of an issue for Blueprints, but I guess we never saw the need to include a `KeyIndexableGraph` because you typically create your indices with the base graph not the wrapper.  I guess for situations where you want to pass a wrapper of a particular interface type to something else, we should have implementations for all wrappers that way.  

Please create an issue in Blueprints.  A pull request would be welcome. :)
