### ISSUE TITLE
Thread.sleep() in Titan LockingTransaction limits throughput

### ISSUE THREAD

**Issue by DanielThomas** [thinkaurelius/titan#69]
I noticed during performance testing Titan that transactions that hold locks sleep for a minimum 100ms on commit and has the effect of limiting Titan throughput:

```
"application-akka.actor.default-dispatcher-150" prio=10 tid=0x00007f0d8856d000 nid=0x3147 waiting on condition [0x00007f0e57cc7000]
   java.lang.Thread.State: TIMED_WAITING (sleeping)
        at java.lang.Thread.sleep(Native Method)
        at com.thinkaurelius.titan.diskstorage.locking.LockingTransaction.sleepUntil(LockingTransaction.java:344)
        at com.thinkaurelius.titan.diskstorage.locking.LockingTransaction.verifyAllLockClaims(LockingTransaction.java:206)
        at com.thinkaurelius.titan.diskstorage.cassandra.CassandraEmbeddedOrderedKeyColumnValueStore.mutateMany(CassandraEmbeddedOrderedKeyColumnValueStore.java:283)
        at com.thinkaurelius.titan.diskstorage.writeaggregation.BufferStoreMutator.flushInternal(BufferStoreMutator.java:81)
        at com.thinkaurelius.titan.diskstorage.writeaggregation.BufferStoreMutator.flush(BufferStoreMutator.java:75)
        at com.thinkaurelius.titan.graphdb.database.StandardTitanGraph.save(StandardTitanGraph.java:637)
        at com.thinkaurelius.titan.graphdb.transaction.StandardPersistTitanTx.commit(StandardPersistTitanTx.java:159)
        - locked <0x000000078fc81758> (a com.thinkaurelius.titan.graphdb.transaction.StandardPersistTitanTx)
        at com.thinkaurelius.titan.graphdb.blueprints.TitanBlueprintsTransaction.stopTransaction(TitanBlueprintsTransaction.java:26)
        at com.thinkaurelius.titan.graphdb.blueprints.TitanBlueprintsGraph.stopTransaction(TitanBlueprintsGraph.java:37
        ...
```

A brief read of the code seems to indicate lock seniority, ie. that a lock was gained _first_, is the priority. Reading the Javadocs on LockingTransaction#writeBlindLockClaim and GraphDatabaseConfiguration for the lock-\* settings, I can only assume the sleep is to ensure that the storage implementation has consistency written (or more precisely, will consistently read) the lock claims for the current transaction:

> This value should be a small multiple of the average consistent write time.

Even if I'm misunderstanding the purpose of this sleep, if a consistency guarantee is needed for reads and writes, shouldn't that be left to the storage implementation, rather than imposing a fixed sleep time? Cassandra is running with QUORUM consistency levels by default, but given configurable consistency, there should maybe be a separate configuration for lock r/w consistency.

Given QUORUM read/write consistency levels, I _think_ it's valid to measure local cfstats read and write latency for the keyspace, which is a fraction of a millisecond:

```
Keyspace: titan
        Read Count: 48021555
        Read Latency: 0.03439590556782262 ms.
        Write Count: 30561038
        Write Latency: 0.01925255631042375 ms.
        Pending Tasks: 0
```

I haven't had the chance to change this setting to determine the contribution, but certainly with workloads that involve reasonable concurrency during edge adds to single super-ish nodes, I've found it difficult to hit system resource limits, which is apparently due to these sleeps.

**Comment by DanielThomas** [comment]
I read the verifyAllLockClaims() Javadoc again, and the sleep definitely seems to be about ensuring that the read value and expectedValue match:

> For each object in the lockClaims list, this method checks (1) that the current transaction indeed holds the lock globally (that is, that the lock claim we wrote to the backing key-value store is indeed the most senior or earliest such claim) and (2) that the expectedValue originally supplied in the locking request matches the current value stored at the key-column coordinate of the lock.

**Comment by mbroecheler** [comment]
The reason for the sleep is as follows: When acquiring a lock, a transaction first applies for the lock. It then reads back all lock applications to see if its application was successful. Its considered successful if its timestamp is the oldest (plus some ip+port based conflict resolution). Now, since we have no guarantees from the storage backend in terms of when writes are going to be accepted, we have to wait a little bit between filing an application and checking its success so that any other transaction that might have filed an application one ms before us but whose write took longer does not succeed after we already read the application back. That's what the sleep is for.

The implementation we have in Titan is purposefully kept very general so that it works against different storage backends. With that generality comes some inefficiency. But even a pure cassandra implementation would need to wait in order to account for possible write latencies which can vary quite a bit.

Now, the default wait time of 100ms is very, very pessimistic. You should be able to successfully use much lower values here. The trade-off is basically this: the lower the wait time, the more lock application might fail because the quorum write takes longer than the specified wait time (we fail the application in that case to ensure correctness). The higher the wait time, the longer the latency introduced by the lock. So, try reducing the wait time and check the logs for how many lock applications failed as a consequence. No worries, correctness should be ensured at all times.

That said, note three things:
1) The wait time should have fairly little impact on throughput as it only affects individual transaction latency. 
2)  Titan is not optimized for acquiring a ton of locks. Locking should be used with great care as it inevitably introduces bottlenecks in the application. If you need a lot of locks, using an additional Zookeeper instance will give you better performance
3) Often times, you don't need to acquire locks during batch loading. Setting batch-loading to true also disables locking (amongst other things). Note sure if that applies here.

**Comment by dalaro** [comment]
This sleep exists for the general case where multiple Titan processes share a single logical storage backend (which may be distributed in turn) and where the Titan processes can't assume their writes are non-conflicting due to some external constraint (like batch loading).  This is implicit in Matthias's answer.  I think it's worth making explicit.  With just one Titan process, there's no point either in sleeping or in writing lock claims to the storage backend, since lock contention should be resolved in memory by LocalLockMediator.

Here's an example of how the exclusion property of some lock L can be violated in the absence of this sleep.  Consider two Titan processes A and B contending for a lock. Their system clocks are synchronized as closely as NTP allows.

A begins writing a claim for L with timestamp T.
B begins writing a claim for L with timestamp T+1.
B's write finishes.
B runs verifyAllLockClaims() and finds itself as the only claimant on L. B concludes that it holds L.
A's write finishes. A has just placed a claim on L with an earlier timestamp than on B's claim.
A runs verifyAllLockClaims() and finds claims on L from both A (itself) and B. The timestamp on A's claim is earliest among the claims on L. A concludes that it holds L.

A and B concurrently think that they hold the same lock.

The code you're pointing to prevents this scenario. The sleep is half of it. The other half is in writeBlindLockClaim().  This method forces a lock claimant to consider invalid those of its claims which take longer than the timeout to write to the storage backend.  These paired constraints mean that B usually won't start verifying its lock claims until A has finished writing, and even when B occasionally does so, A is forced to discard its "late" claim (the one that torpedoed B above).

**Comment by DanielThomas** [comment]
Guys, thanks, this is excellent. 

I'm not familiar enough with Cassandra consistency/read repair/reliability of write statistics to really weight in on whether this is something that could be addressed at a storage layer or automatically tuned based on reported write latencies.

I watched Matthias' C\* presentation and noticed he called this out, is this tuning documented in the wiki?

**Comment by mbroecheler** [comment]
Uh, I like your thinking on the automatic tuning of the lock write latency
timer. But that will be a Titan 2.0 feature ;-)

For now, I suggest you have a look at your cassandra quorum write latencies
under medium stress and set the value to the mean + X std deviations where
X is your measure of "conservativeness", i.e. a high value of X means that
only a very tiny percentage of lock acquisitions will fail but each
acquisition incurs a higher latency. I would suggest to start with X=4
which is fairly conservative.
But this very much depends on your application. If you want to get lower
latencies but don't mind retrying transactions (and titan 0.1 will do that
automatically for you) you can be more aggressive and use lower X.

The mean and standard deviation will depend greatly on your network
infrastructure and expected load. The reason we used a very, very
conservative time of 100ms is because we expect users to try Titan on EC2
which sometimes has notoriously bad latencies. Your environment will
probably be much better behaved.

We are currently in the process of updating the wiki for the upcoming
release. I will include more information on this topic.

On Tue, Sep 4, 2012 at 3:16 AM, Danny Thomas notifications@github.comwrote:

> Guys, thanks, this is excellent.
> 
> I'm not familiar enough with Cassandra consistency/read repair/reliability
> of write statistics to comment on whether this is something that could be
> addressed at a storage layer or automatically tuned based on reported write
> latencies.
> 
> I watched Matthias' C\* presentation and noticed he called this out, is
> this tuning documented in the wiki?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/thinkaurelius/titan/issues/69#issuecomment-8258281.

## 

Matthias Broecheler, PhD
http://www.matthiasb.com
E-Mail: me@matthiasb.com

**Comment by DanielThomas** [comment]
Great advice, thanks Matthias.
