### ISSUE TITLE
Simplify the reindexing process

### ISSUE THREAD

**Issue by dkuppitz** [thinkaurelius/titan#709]
It would be nice to have the following code snippet (taken from the [docs](http://s3.thinkaurelius.com/docs/titan/0.5.0-SNAPSHOT/reindex.html)) wrapped in a single method call:

``` groovy
// Block until the SchemaStatus transitions from INSTALLED to REGISTERED
registered = false
before = System.currentTimeMillis()
while (!registered) {
    Thread.sleep(500L)
    mgmt = g.getManagementSystem()
    idx  = mgmt.getGraphIndex("mixedExample")
    registered = true
    for (k in idx.getFieldKeys()) {
        s = idx.getIndexStatus(k)
        registered &= s.equals(SchemaStatus.REGISTERED)
    }
    mgmt.rollback()
}
```

**Suggestion:**

``` groovy
// Block until the SchemaStatus transitions from INSTALLED to REGISTERED
mgmt = g.getManagementSystem()
mgmt.getGraphIndex("mixedExample").await() // perhaps with an optional timeout:
//   .await(10000) throwing a TimeoutException if the process doesn't finish within the
// given time span
```

**Comment by dalaro** [comment]
The API might be a little different than shown above.  We should support configuration of the sleep interval, timeout, and objective status.  An overload with sensible defaults is fine as long as we allow setting the others.  The timeout might be approximate in some configurations due to retry loops further down the stack, such as in BackendOperation or Astyanax.  For general use, we should add log statements in each outer loop iteration listing the keys that still haven't converged.

**Comment by dalaro** [comment]
@mbroecheler can and should this be done safely inside a singe ManagementSystem, i.e. without getting foiled by cache on repeated getFieldKeys() and getIndexStatus calls?  I kept opening and rolling back management systems as shown in the snippet because I wasn't certain schemata caching was disabled inside a single ManagementSystem for these reads.  I've looked through the code for about a half hour, but I'm still not even close to checking all of the code paths on the field key and index status implementations.

I'm asking because this has implications for the helper method signature: static if we need to keep reopening ManagementSystems, possibly a non-static method on ManagementSystem if it's suited to a single MS instance.

**Comment by dalaro** [comment]
discussed with @mbroecheler, it's best to close and reopen ManagementSystem often; it does cache, and it should not be held open longer than necessary to avoid obstructing tx-closure-dependent ops

**Comment by dalaro** [comment]
I added a pair of utility classes for this:
- GraphIndexStatusWatcher
- RelationIndexStatusWatcher

To make their use in the shell a bit more concise, I also added public static ManagmentSystem methods:
- ManagementSystem.awaitGraphIndexStatus
- ManagementSystem.awaitRelationIndexStatus

An example invocation from the docs:

``` groovy
mgmt.awaitGraphIndexStatus(g, "mixedExample").call()
```

There are setters for controlling the target status (defaults to `REGISTERED`), timeout (defaults to 1 minute), and fixed polling interval (defaults to 500 ms).
