### ISSUE TITLE
"Use Titan's Management API to create indices"

### ISSUE THREAD

**Issue by asaf** [thinkaurelius/titan#714]
Hey,

This is a feature request, to support standard Blueprints API for managing indices,

We'r in a migration process from Neo to Titan and the main reason why this is possible at all without rewrite is thanks to Blueprints,

Not supporting the generic API layer Titan was built on sounds weird to me (unless there's a very good reason)

Support was gone in 0.5.0,

Thanks.

**Comment by spmallette** [comment]
going forward in tinkerpop3, tinkerpop APIs will not support indexing at all.  the vendor indexing APIs are all too varied in what they require to keep the tinkerpop ones generic while still robust.  i have a feeling this was a planned move from @mbroecheler given the upcoming shift to TP3 focus.  

that said, if you are migrating to titan and are not taking advantage of the native api interface, you won't have a great experience.  dig into the titan indexing features as they offer a vast extension over the very limited `createKeyIndex` feature of Blueprints.  furthermore, you will see big performance improvements if you advance your schema beyond basic indices.

i'm sure @mbroecheler will reopen this or comment otherwise if i'm off base here.

**Comment by asaf** [comment]
@spmallette Thanks for answering,

I understand the complexity of having support for multi vendor within a generic API, and 
while I dig more and more into Titan, the data type is too different from Neo and other dbs I've seen so far.

Thanks again.

**Comment by mbroecheler** [comment]
Stephen is exactly right. Also note that the schema and index creation code
is typically a small subset of the application that gets executed once and
hence the amount of vendor lock in is rather minimal.

And, as Stephen noted, you would typically want to use database specific
features. For Titan, a lot of what makes is scalable less in the schema and
indexes.
