### ISSUE TITLE
Few issues related to checking edge/keys existence.

### ISSUE THREAD

**Issue by asaf** [thinkaurelius/titan#731]
Hey,
1. When `schema.default` is set to default, tm.getPropertyKey() creates the key if it doesn't exist,
   IMO this is confusing as getters usually retrieve content and don't perform actions,
   I was trying to invoke this method to create a key if it doesn't exist and the invocation itself created an Object key.
2. When `schema.default=none`, tm.getPropertyKey() fails if key doesn't exist,
   It could be nice to have a silent boolean method such as `containsPropertyKey`, we have this for the `containsVertexLabel`
3. Same goes for `getEdgeLabel`, i'll be nice to have a boolean `containsEdgeLabel` method.

Thanks.

**Comment by mbroecheler** [comment]
For 2) + 3): There is the method containsRelationType(String) which
generalizes containsPropertyKey and containsEdgeLabel since both live in
the same namespace.

On Mon, Aug 25, 2014 at 1:06 PM, Asaf Shakarchi notifications@github.com
wrote:

> Hey,
> 
>    1.
> 
>    When schema.default is set to default, tm.getPropertyKey() creates the
>    key if it doesn't exist,
>    IMO this is confusing as getters usually retrieve content and don't
>    perform actions,
>    I was trying to invoke this method to create a key if it doesn't exist
>    and the invocation itself created an Object key.
>    2.
> 
>    When schema.default=none, tm.getPropertyKey() fails if key doesn't
>    exist,
>    It could be nice to have a silent boolean method such as
>    containsPropertyKey, we have this for the containsVertexLabel
>    3.
> 
>    Same goes for getEdgeLabel, i'll be nice to have a boolean
>    containsEdgeLabel method.
> 
> Thanks.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/thinkaurelius/titan/issues/731.

## 

Matthias Broecheler
http://www.matthiasb.com

**Comment by asaf** [comment]
@mbroecheler Thank you for answering, I'm not sure why both live in the same namespace but I assume this is related internally to how titan structures the graph elements,

Either way, if you guys feel okay with the behavior of 1 then close this issue, I found it very confusing, up to you :-)

Thanks!

**Comment by mbroecheler** [comment]
from @spmallette 

matthias, i was converting some older Titan schema creation code to Titan 0.5.  to check key existence, i naively did (because that's what i did before basically):

def t = mgmt.getPropertyKey("someName")
if (t == null) {
   // create

when i ran this, i got this exception:

java.lang.IllegalArgumentException: Property Key with given name does not exist:someName
at com.thinkaurelius.titan.graphdb.types.typemaker.DisableDefaultSchemaMaker.makePropertyKey(DisableDefaultSchemaMaker.java:27)
  at com.thinkaurelius.titan.graphdb.transaction.StandardTitanTx.getPropertyKey(StandardTitanTx.java:817)

i thought that's ok - i'll just catch the exception, but then i looked at the stack trace more carefully and it looks like Titan tries to create the key and that i was only saved from wrongly constructing it because i had schema.default=none in my config  

I asked Mr. Kuppitz about it and he said the proper method for checking keys is with:

if (!mgmt.containsRelationType("someName")){    mgmt.makePropertyKey("someName").dataType(String.class).make();
}
so - i'll make my code look like that, but i think that perhaps it might be better if getPropertyKey() didn't imply construction even if the schema is inferred.  I get that a key should get created if i do: 

g.addVertex('someName",'marko")

but it seems kinda strange from the perspective of the Management api.  Anyway, just a thought and something to consider.

**Comment by huiwenhan** [comment]
I have same problem with @asaf ,home Titan can enhance in next release !

and when will 0.5.1 release ?

**Comment by mbroecheler** [comment]
getPropertyKey and related methods do no longer create the types if they don't yet exist. Separate methods called getOrCreatePropertyKey() assume the old semantics.
