### ISSUE TITLE
Gremlin Console Problem

### ISSUE THREAD

**Issue by PseudoCorps** [thinkaurelius/titan#742]
I'm on titan-0.5.0-hadoop2 
When I execute 

```
g = TitanFactory.open("conf/titan-cassandra-embedded-es.properties")
```

from the gremlin console, the following input does not appear. However, the console does continue to function properly. For example, if I enter:

```
g.V
```

the characters don't appear, but if I hit return the command still runs properly. 
I think this might be a problem because after I leave the console, the behavior continues. I'm not sure if this is just a graphics issue or not, but it seems like there is a memory leak.

Running the following reactivates the text

```
stty -echo
```

**Comment by dalaro** [comment]
I've seen a slightly different problem: ctrl+c inside gremlin.sh exits promptly, but it often leaves the terminal with echo disabled.  At that point I either blind-type `stty sane` (similar to what you're doing) or exit the terminal.  I long assumed that was due to a nonexistent or missed shutdown hook to restore terminal state... this problem likely involves jline or the way gremlin.sh uses jline, though I'm not certain.

But it sounds like you're describing a much more severe problem.  Let me describe the problem you're reporting to make sure that I understand: starting gremlin.sh and then just executing

```
g = TitanFactory.open("conf/titan-cassandra-embedded-es.properties")
```

disables echo _inside_ gremlin.sh, such that input on subsequent `gremlin>` prompts in the same session isn't displayed?  That I've yet to see.

Can you share some more details about your environment?  How about:
- value of `$TERM`
- the terminal emulator program
- OS
- whatever else you deem relevant

**Comment by PseudoCorps** [comment]
Its happened on my mac and on Ubuntu xterm
I think it might be a weird interaction between the daemons reporting an error and the gremlin console console.
One of the things I was doing wrong was running the titan server thinking that the cassandra-es option ran the embedded version, I would then go into the console and try to load the embedded properties. Which I think was probably starting two embedded conflicting stacks.
I was trying to run the full embedded stack, but I'm not if my work around is actually configuring it properly.

I first copied the file 

```
cp conf/rexster-cassandra-es.xml conf/rexster-cassandra-embedded-es.xml
```

It fixes the part where the titan script inputs the config for the rexster file. After you can run 

```
bin/titan.sh -c cassandra-embedded-es start
```

Which seems to start without a problem, and I then go into gremlin and (correct me if I'm wrong) connect to the thrift interface of the running stack

```
g = TitanFactory.open('conf/titan-cassandra-es.properties')
```

which seems to connect properly. I guess I'm just wondering now if this is actually building with rexster cassandra and titan all in the same instance as described by the 4th example on this page?

```
https://github.com/thinkaurelius/titan/wiki/Using-Cassandra
```
