### ISSUE TITLE
Print warning or fail to start when a GLOBAL_OFFLINE property is modified in config.

### ISSUE THREAD

**Issue by rjbriody** [thinkaurelius/titan#743]
"GLOBAL_OFFLINE options get written to the storage backend on Titan's first startup, and further changes in the config file have no effect." -Dan LaRocque

This can be tricky for a user who doesn't realize why their config file changes are not taking effect. Maybe we should print a warning, or possibly even fail to start all together.

Discussion here:
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/aureliusgraphs/Zbd87qNKOUM/WhjGD9vqzH8J

**Comment by armisael** [comment]
+1 for the "fail to start" solution, I've lost four hours trying to figure out why my `index.search.hostname` property was not read properly (apparently it is a `GLOBAL_OFFLINE`, while `index.search.port` is `MASKABLE`)

**Comment by dalaro** [comment]
I agree that Titan should warn.

I'm not convinced that we should fail to start.  Consider deploying a cluster of Titan hosts with a config file that customizes `storage.lock.expiry-time`.  This is a `GLOBAL_OFFLINE` setting whose ideal value depends on the storage backend's write latency.  It's usually site-specific and subject to customization.  Suppose that, after bootstrapping, I find out that I underestimated the average write latency on my cluster's network/backend.  I increase the value through `ManagementSystem`.  Now my Titan processes die on restart due to the old value in their config files.  I have to push an updated file to get them back online.

I added a new boolean option `graph.allow-stale-config`, that controls fail-to-start behavior.  When false, Titan will die during startup with a `TitanConfigurationException` if it finds one or more options in the local config with mutability `GLOBAL`, `GLOBAL_OFFLINE`, or `FIXED` whose values differ from the corresponding values in the storage backend's copy of the configuration.  It also logs each option at severity `ERROR` just before throwing.  When true, Titan still logs a warning for each discrepancy, but it starts up normally.  The default is true.

Here's sample output under allowed-to-start behavior (current default):

```
0   [main] WARN  com.thinkaurelius.titan.graphdb.configuration.GraphDatabaseConfiguration  - Local setting tx.max-commit-time=Duration[456 ms] (Type: GLOBAL) is overridden by globally managed value (Duration[10 s]).  Use the ManagementSystem interface instead of the local configuration to control this setting.
```

Here's sample output under fail-to-start behavior:

```
0    [main] ERROR com.thinkaurelius.titan.graphdb.configuration.GraphDatabaseConfiguration  - Local setting tx.max-commit-time=Duration[456 ms] (Type: GLOBAL) is overridden by globally managed value (Duration[10 s]).  Use the ManagementSystem interface instead of the local configuration to control this setting.
com.thinkaurelius.titan.core.TitanConfigurationException: Local settings present for one or more globally managed options: [tx.max-commit-time].  These options are controlled through the ManagementSystem interface; local settings have no effect.
```

**Comment by rjbriody** [comment]
Adding documentation to the example config files would probably help a lot
as well. I'm thinking there might be:
- a link to the "Global Configuration" Titan docs page
- a short warning: "Properties of type GLOBAL, GLOBAL_OFFLINE, and FIXED
  are stored in the backend on first startup. Modifying these properties here
  will have no effect after Titan is initialized."
- then as a bonus, a label identifying the type of each property

That, coupled w/ the warning at startup, would have prevented confusion in
the cases I saw so far.

Bob

**Comment by dalaro** [comment]
"a short warning: ..." in comments in the example config files?  Or elsewhere?

**Comment by rjbriody** [comment]
Each of those bullets are suggestions for the example config files.

**Comment by dalaro** [comment]
a8bad29d01dd4ab1c0e25b0c25738e72f9b55e05 tweaks the Maven assembly input to let us do some basic templating with `ConfigOption` info.

Lines like this in the config sources

```
#TITANCFG{storage.backend=cassandrathrift}
```

are converted like this in the output ("output" is the files in zipfile/conf and $REPO_ROOT/conf):

```
# The primary persistence provider used by Titan.  This is required.  It
# should be set one of Titan's built-in shorthand names for its standard
# storage backends (shorthands: berkeleyje, infinispan, cassandrathrift,
# cassandra, astyanax, hbase, embeddedcassandra, inmemory) or to the full
# package and classname of a custom/third-party StoreManager
# implementation.
#
# Default:    (no default value)
# Data Type:  String
# Mutability: LOCAL
storage.backend=cassandrathrift
```

A warning is automatically appended when the mutability is `GLOBAL`, `GLOBAL_OFFLINE`, or `FIXED`.  Here an example for `GLOBAL_OFFLINE` (`GLOBAL`'s warning looks the same; `FIXED` prints "This setting is FIXED and cannot be changed after bootstrapping Titan." instead):

```
# The Elasticsearch node.client option is set to this boolean value, and
# the Elasticsearch node.data option is set to the negation of this value.
# True creates a thin client which holds no data.  False creates a regular
# Elasticsearch cluster node that may store data.
#
# Default:    true
# Data Type:  Boolean
# Mutability: GLOBAL_OFFLINE
#
# Settings with mutability GLOBAL_OFFLINE are centrally managed in Titan's
# storage backend.  After starting the database for the first time, this
# file's copy of this setting is ignored.  Use Titan's Management System
# to read or modify this value after bootstrapping.
index.search.elasticsearch.client-only=true
```

I also wired validation into the titan-dist build.  Right after the template utility executes, `ConfigurationLint` runs on the output file to validate it.  This checks that it parses as a `PropertiesConfiguration`, that every key inside corresponds to a `ConfigOption`, and that the verification predicate for each `ConfigOption` accepts the associated value.  That last bit is new.  Now if we write a value which fails the `ConfigOption`'s predicate, that will be detected before building the zipfiles.  For example, writing

```
#TITANCFG{graph.timestamps=FOO}
```

or bypassing the template system and just writing

```
graph.timestamps=FOO
```

in one of the sample configs will produce a `ConfigurationLint` failure that aborts the titan-dist build.  This is an improvement over the previous version of `ConfigurationLint`, which checked keys but not the values.

**Comment by rjbriody** [comment]
@dalaro you are the man!

**Comment by dmarkwat** [comment]
I finally found this issue after a few hours of puzzling over my config changes in Titan; I was trying to change my index backend from local to Solr and then a variety of changes to the Titan-Solr config - each time, blowing away the database after giving up from simply restarting Titan.

But in the docs, [Titan 0.5.2](http://s3.thinkaurelius.com/docs/titan/0.5.2/configuration.html#configuration-global), I am noticing GLOBAL_OFFLINE says "changing these options requires a cluster restart to ensure that the value is the same across the entire cluster," which seems contrary to the comment at the opening of this issue.

Is the doc not up to date?  Or am I miss something simple?

**Comment by dalaro** [comment]
@dmarkwat I thought the docs and the comment at the start of this issue seemed consistent.  Can you elaborate on the specific contradiction or misunderstanding?  Maybe we can expand the docs to address it better.

BTW, did you receive a warning like the following when invoking `TitanFactory.open` while struggling with config changes?

```
WARN  com.thinkaurelius.titan.graphdb.configuration.GraphDatabaseConfiguration  - Local setting index.search.elasticsearch.client-only=true (Type: GLOBAL_OFFLINE) is overridden by globally managed value (false).  Use the ManagementSystem interface instead of the local configuration to control this setting.
```

This sort of message -- albeit citing a different config option in the specific case you described -- should be logged on 0.5.1 and later.

**Comment by dmarkwat** [comment]
I did see that line, yes - took a while but I did see it which led me to dig until I found this.

In summary I'm reading the docs as "GLOBAL_OFFLINE properties in the config file can be changed and will take effect once the cluster is completely turned off and comes online again" and I'm reading the quote from above as "once a GLOBAL_OFFLINE property is set and the Titan cluster is initialized, any changes to those properties will never take effect in that cluster, even if the cluster were to be restarted".

Short example:
I initialize my Titan db; in the config file I have a property: index.search.backend=elasticsearch
I shut down Titan
I change this same property in the config file to: index.search.backend=solr
I start Titan again

Which is the effective value used by this titan cluster for the property index.search.backend?  'elasticsearch'?  or 'solr'?

I hope I'm not making this more confusing - please let me know if this is the case.

**Comment by dalaro** [comment]
In response to your question: elasticsearch.

GLOBAL_OFFLINE options (of which `index.search.backend` is one example) can be changed through the `ManagementSystem` API.

Instead of shutting down Titan and modifying the local config file, do the following on a single Titan instance (any will do):

```
mgmt = g.getManagementSystem()
mgmt.set('index.search.backend', 'solr')
mgmt.commit()
```

Then shutdown all Titan instances, including `g` from the snippet above.  When Titan is restarted, it should use Solr.

I think one contributor to confusion here is ambiguity about how Titan stores configuration data.  There are two sources of configuration information:
- the configuration file
- the storage backend (on Cassandra, for example, Titan maintains a CF containing configuration data)

During Titan's first run, the storage backend gets a copy of the contents of the configuration file (except options marked LOCAL).  The storage backend's copy of the config is effectively shared between all instances.  It's only automatically populated from the local config file during that first Titan run.  After that, changes to the storage backend copy of the config must be done manually through the `ManagementSystem`.

Does that do anything to resolve the confusion?

**Comment by dmarkwat** [comment]
Sorry for the delay on this!  Yes, that makes perfect sense and clears up the confusion.  Thanks very much for the information and assistance.
