### ISSUE TITLE
Extend Locking Test coverage

### ISSUE THREAD

**Issue by mbroecheler** [thinkaurelius/titan#76]
Considering a multi-threaded stress-test type case and perhaps cases that tweak the timing variables -- using various expiration and wait times, for instance.

**Comment by mbroecheler** [comment]
some additional tests have been added as part of bug fixing. More to come.

**Comment by mbroecheler** [comment]
ensure that all locks are released and everything is properly rolled back upon transactional failure

**Comment by dalaro** [comment]
Since then and now, I rewrote the locking code with TDD.  The locking logic is tested with all collaborator objects mocked or stubbed: https://github.com/thinkaurelius/titan/blob/master/titan-test/src/test/java/com/thinkaurelius/titan/diskstorage/locking/ConsistentKeyLockerTest.java.  The test is single-threaded and deterministic, but it tests wait timeouts and expirations by stubbing System.currentTimeMillis() (among other calls).

When I rewrote the code and introduced the Locker interface, I also maintained existing KCVS acquireLock() and mutate() semantics through ExpectedValueCheckingStore.  So the old LockKeyColumnValueStoreTest class is still in the tree and still passes.  This class is a combination of single-threaded tests of basic lock semantics and multi-threaded  "stress test" type integration tests.  That gives us some coverage at the diskstorage layer.

Maybe we could still use lock-focused coverage at the graphdb layer.  I think BackendTransaction/BackendOperation timeout and retry behavior isn't deliberately stressed yet.
