### ISSUE TITLE
Error scanning classpath with Reflections

### ISSUE THREAD

**Issue by ghost** [thinkaurelius/titan#791]
titan-cassandra has a dependency on Reflections library. When the app starts Reflections library scans classpath. I am assuming it is looking for annotations. It also tries to scan the working directory. This works fine if it has permissions to scan working directory. If it does not have permissions then it fails silently and app fails to start. 

This is happening for me when running the app as a service and the working directory is file:/

Working directory is not on the classpath so I don't think it should be scanning it. If it must it should at least output an error when it fails.

**Comment by dalaro** [comment]
Can you send exact steps to reproduce this, including the version of Titan used and the full permissions bitmask on the working directory?

I included a bogus config option `foo=bar` in titan-cassandra.properties to force Reflections to do a full walk over the classpath.  I used titan-0.5.1-hadoop2.zip.  I tried as a regular user with my / (which is root/root 755) and with an empty directory called execonly that was root/root 711.  The behavior you reported didn't appear in either case.

Minor point: titan-cassandra depends on titan-core which depends on reflections.  The code that uses it is only in core.  So titan-cassandra does indirectly/transitively depend on reflections, but it does not have a direct dependency, and this bug would theoretically affect the other storage backends just the same since the code involved should be in core.

**Comment by ghost** [comment]
This may have been caused by an error in our configuration. Changes to our classpath setting in start script fixed the issue.
