### ISSUE TITLE
Implement ACID support with PostgreSQL

### ISSUE THREAD

**Issue by calbazasebastian** [thinkaurelius/titan#795]
I would like to use Titan with a backend that suports ACID, but BDB is not really an option because of it's license...
Was thinking that it would be a good ideea to use PostgreSQL and it's hstore datatype.
There is a lot of documentation on implementing graphs in a relational database and  by using hstore property graphs are also easy to do.

Would it be possible to have this in the near future?

Sebi

**Comment by scottauchmoody** [comment]
I'm in the process of building a PostgreSQL backend for Titan.
What is the process for submitting my change for consideration? 
Or is this something already being worked on by someone?

**Comment by mbroecheler** [comment]
Hello Scott,

I don't think anybody is currently working on a PostgreSQL backend. It
probably be best if you make the storage backend available as a github
repository for users to try out. We'd be happy to link to it from the
documentation.
Depending on the community feedback and your continued involvement, we can
discuss merging it into the Titan codebase. Based on past experience, we
won't directly merge such significant contributions since we might end up
being "stuck" with those and unable to maintain.

Thanks for your effort,
Matthias

**Comment by ghost** [comment]
Hi Scott,

Following up on your PostgreSQL work.  I didn't see this work in your public repo.  Were you able to complete the PostgreSQL backend ?

**Comment by spmallette** [comment]
closing - given matthias' earlier reply.  would be nice to hear if there's been any work on this though externally.

**Comment by scottauchmoody** [comment]
Matthias,
We decided to go a different route and didn't pursue using postgres to
backend Titan.
--Scott
