### ISSUE TITLE
S3 Integration Docs for titan-hadoop Missing

### ISSUE THREAD

**Issue by spmallette** [thinkaurelius/titan#797]
Not sure if this was intentional, but this page from Faunus:

https://github.com/thinkaurelius/faunus/wiki/Using-Amazon-S3-for-Storage

Doesn't appear to have been migrated to the latest titan-hadoop docs.  The functionality still appears to work so it doesn't look like it was removed.

**Comment by dalaro** [comment]
I ported this to titan05 as docs/faunus/s3.txt (a0a726d2fdc0dd20e82dee4536701064f4f778e7).

Since this page is applicable to older versions, I also cherry-picked this to 0.5.0_docs and 0.5.1_docs local branches that I've been keeping off their respective release tags.  Thanks to non-numeric page names and hyperlinks, we can add chapters retroactively without breaking existing deep links.  Newly uploaded S3 chapters for past 0.5.x releases:

http://s3.thinkaurelius.com/docs/titan/0.5.0/hadoop-s3.html
http://s3.thinkaurelius.com/docs/titan/0.5.1/hadoop-s3.html

The code and markup looked OK to me, and the links haven't rotten, but please do reopen if you see something that I missed.
