### ISSUE TITLE
Entire Kryo dependency should be shaded

### ISSUE THREAD

**Issue by philmes** [thinkaurelius/titan#821]
Titan depends quite intimately on a specific version of Kryo. Unfortunately Kryo isn't as backwards compatible as it ought to be, and there are some nasty hard conflicts with the version used by, amongst other things, Twitter Scalding and Cascading.

Ideally Kryo should be shaded, or there should be a `titan-all` style dependency which includes all of the core dependencies shaded into the jar.

**Comment by curtisallen** [comment]
Sounds like a good idea but Kryo makes heavy use of reflection which can be immune to shading. I've ran into classpath issues with differing versions of kryo and the only solution was to make sure only one version of kryo is on the classpath.

**Comment by philmes** [comment]
Yep. Unfortunately in this case, there are binary and source incompatibilities between the version of Kryo that Titan depends on, and the version that Scalding depends on (I tried patching the latter but it turned into a bit of a rabbit hole). FWIW, I have created a shaded version of Titan 0.5.1 and it all seems to work fine.

**Comment by dalaro** [comment]
I have noticed Kryo's shading approach changing since about 2.22, when its "shaded" artifact classifier disappeared.  2.22's primary artifact appeared to include shaded copies of Kryo's dependency tree, including objenesis, reflectasm, and minlog, much like the old jar with the "shaded" classifier.  That changed in 2.23.0, when shaded objenesis was removed, and again in 2.24.0, when shaded minlog was removed, leaving only shaded reflectasm.

If Titan's target Kryo can be safely shaded, I would be in favor.  As @curtisallen points out, this might not be possible for nontrivial reasons.  I don't know why upstream stopped shading, but if it was motivated by some deep technical limitation I don't know about, then we could have a problem.  Needs additional investigation.

On the other hand, I'm starting to wonder if every dependency that uses ASM needs to be shaded (#784, #361).

**Comment by curtisallen** [comment]
Interesting @dalaro , unfortunately  we'll probably be stuck playing these types of games until we have access to Jigsaw in java 9 :cry: 
Hopefully you can get some solution working before then.

**Comment by philmes** [comment]
Just for clarity as I see this issue was reference from #828 - this problem is about Kryo itself conflicting, not it's dependencies. Scalding (and a bunch of other Twitter Hadoop libraries) depend on an older version of Kryo which isn't binary compatible with the version Titan uses.

**Comment by mbbeaubi** [comment]
I'd just like to chime in and vote for this as well. If not possible to shade, would it be possible to downgrade titan to kryo 2.21? That's the version that twitter chill uses, which is in turn used by spark, storm, and cascading. None of these can work with titan until this issue gets resolved.

**Comment by mbroecheler** [comment]
We decided to remove the (direct) dependency on Kryo for 0.9. This will make it incompatible with previous releases but also make life much easier moving forward in terms of upgrade and data compatibility.

**Comment by curtisallen** [comment]
@mbroecheler are you referring to previous releases of titan or kryo?

**Comment by mbbeaubi** [comment]
Wow, I was just working merging the changes in my custom titan branch where I've shaded kryo with the most recent changes you've made in titan05.

Any idea when kryo will be out of .9 so I can start using it?

BTW, the kryo shading solution was working well for me, been using my patched titan for about a month now.

**Comment by dalaro** [comment]
In response to https://groups.google.com/d/msg/aureliusgraphs/qOqFKIXqFok/Ke8e2KifHNUJ, I think the right fix is to shade Titan's copy of Kryo (i.e. implement https://github.com/thinkaurelius/titan/issues/821 as originally reported on titan05).  I have a local titan05 branch with shaded Kryo that resolves the issue described in that thread, as tested with a trivial count-vertices Spark application fed by TitanCassandraInputFormat using Spark's InputFormat-to-RDD converter.  This is probably much the same as what @mbbeaubi was working on, although I haven't seen that.

This would be a disruptive change.  Users who currently rely on titan-core to bring in the unshaded Kryo 2.22 dependency would have to manually declare that dependency in their own projects.  Besides, there's a nagging risk of unforeseen consequences when shading Kryo, or any core component; even if the full test suite passes (still going here), classfile rewriting is an intrinsically dicey proposition and its safety is not trivial to prove.

However, assuming there are no test failures or other defects, I think it's probably necessary.  titan05 and Spark 1.2.1 depend on slightly different Kryo versions: 2.22 and 2.21, respectively.  Titan apps running on Spark appear to use the version of Kryo that ships with Spark as opposed to their own.  It's not reasonable to expect users to recompile Spark with a different Kryo version to match Titan (it doesn't appear totally trivial to do that either, since my least-effort Spark pom tweak failed to compile).  It is reasonable to expect minor differences in Kryo versions used at read and write times to result in exceptions a la #615.  Shading should protect against that.

**Comment by dalaro** [comment]
Repository with the smallest Spark job I could concoct that reads from Titan using TitanCassandraInputFormat and Spark's InputFormat-to-RDD converter: https://github.com/dalaro/titan-spark-test

**Comment by dalaro** [comment]
Kryo shading is implemented now on titan05 and titan09.

titan05 commits:
- c736cf7dba4b72ba00c9cf8dbe2941be6e9c66a9
- e6e2dacc2b10d4936ebf1ff9d9bdb4d2498ed0d4

titan09 commit:
- af76a295311146f0c3a24453a1b6fc1d0a4f12c3

**Comment by mbbeaubi** [comment]
Excited to see this is finally in. If it gives you any confidence we've been successfully using Spark / GraphX and Titan for 4 months now using custom build of titan 0.5.3 that has kryo shaded with no issues. But it's going to be great to get back on ML.

**Comment by andrewnet** [comment]
Hi dalaro,

Are your commits on titan05 in the titan-0.5.4-hadoop2.zip?

```
c736cf7
e6e2dac
```

I am using "titan-0.5.4-hadoop2.zip" and still has the problem.

**Comment by raviknits** [comment]
@mbbeaubi  - I too have a similar scenario where I am trying to load Titan Graph into GraphX for processing. I am stuck with mapping the FaunusVertex of Titan to EdgeRDD of GraphX.
How did you map Titan's FaunusVertex to Graphx's EdgeRDD for running graph algorithms?
Do you have some custom code which you could share?
