### ISSUE TITLE
Message received response timeoutConnection (3600000 s)

### ISSUE THREAD

**Issue by traykova** [thinkaurelius/titan#834]
Hello,

I'm configuring my RexsterClient in the following way:

Map<String, Object> conf = new HashMap();
conf.put("hostname", "localhost");
conf.put("graph-name", "graph");
conf.put("timeout-connection-ms", 3600000);
RexsterClient client = RexsterClientFactory.open(conf);

However, when I query titan-berkeleydb (using titan-0.5.1-hadoop2), I'm getting the following error:

java.io.IOException: Message received response timeoutConnection (3600000 s)
at com.tinkerpop.rexster.client.RexsterClient.execute(RexsterClient.java:185)

Even though I set up the timeout-connection-ms to 1 hour, the connection still times out in 8 s.

Any idea how this can be fixed?

Thanks,
Simona

**Comment by spmallette** [comment]
This is really a rexster issue - answering on the mailing list: https://groups.google.com/forum/#!topic/aureliusgraphs/xMqU1sbvOnk

**Comment by mikeiannacone** [comment]
I'm having what I suspect is the same issue.

Is there any update on this?

I saw the message you referred to - is there an issue created on another project that addresses this?

**Comment by spmallette** [comment]
@mikeiannacone i'm not sure an issue was opened in Rexster for this because the OP didn't provide any additional information.  i'm pretty sure I did improve the error messaging as I stated in the mailing list post, but I'm not sure that there was much more investigation.

**Comment by mikeiannacone** [comment]
hm.  Around what time frame would that have been?  I'm still seeing  `java.io.IOException: Message received response timeoutConnection (3600000 s)` during my travis-ci tests.  (I bumped the timeout to match the 1h above.)  I'm seeing around 6-8 instances of this message in under 15 minutes of total test run time, so presumably this message is not correct in this case.  (eg. builds 39 and 41 here: https://travis-ci.org/stucco/graph-alignment/builds)

I was previously using Titan 0.5.2, and just confirmed the same on 0.5.3 - is it possible that there's a fix (to the error message at least) that's just not in a released version yet?

If there's any additional info that would be useful, please let me know, since I'm not sure where to start to narrow things down.  The current config files are here if that's helpful: https://github.com/stucco/graph-alignment/tree/development/rexster-config although I've been seeing the same/similar issue for some time, with various config options.

Thanks!

**Comment by spmallette** [comment]
hmmm - looks like it was part of Rexster 2.6.0:

https://github.com/tinkerpop/rexster/commit/831a87c3174112ad60c20f38ede7504059fa0bbd

which Titan 0.5.x doesn't officially support.  i've heard tell of people doing it though without problem...we just haven't officially tested such things.

**Comment by mikeiannacone** [comment]
Nice, thanks!  I'll try that soon.

However, after that, it looks like there's still some Titan issue remaining, which is causing the null `resultMessage` which is being checked for in the updated Rexster code.  (Unless I'm off here - I'm not an expert on titan/rexster internals by any means.)  Any idea how I can start digging into that issue?

I've seen it when using the cassandra and in-memory backends (haven't tried the others) and it seems to occur mainly in the travis-ci environment (perhaps due to resource constraints?)  I'm thinking I should set up a similar VM environment locally so I can reproduce it more conveniently, but even after that I'm still not sure what Titan output I should be looking for.

Any advice?

**Comment by spmallette** [comment]
I think you have to try to recreate this problem off of travis.  We battle with travis all the time when it comes to "integration style" tests (so much so that we have gotten very particular about what tests are executed there - at least for tinkerpop).  The environment is quite unpredictable.

**Comment by mikeiannacone** [comment]
Hm.  I switched the tests over to tinkergraph, to try to avoid this issue, but ran into the same problem on travis.

I also tried to create a VM environment similar to travis, but can't reproduce the issue there.  I'll probably play around with that environment some more and see what I come up with.  (My VM is missing a lot of their default-installed services, so I plan to add those when I come back to it.)

@traykova, any input on what environment you were using when you encountered this?

**Comment by spmallette** [comment]
As this issue seems to be be reproducible with TinkerGraph, it doesn't sound as though it is a Titan issue.    @mikeiannacone if you get any closer to reproducing this outside of travis, please create an issue in Rexster for the discussion to continue there.
