### ISSUE TITLE
Replicas setting in elastic search indices

### ISSUE THREAD

**Issue by BrynCooke** [thinkaurelius/titan#840]
As far as I can tell there is no way of specifying the number_of_replicas setting when indices are created in Elastic Search via Titan. The default is 1.

The user can interact with Elastic Search directly to change this after the index has been created, but I feel that this should be an option within Titan in the same way that replication factor can be set for Cassandra.

**Comment by BrynCooke** [comment]
I can see that in the ES config you can set index.number_of_replicas to set the default in the ES config, but still think that this should be an option in Titan.

**Comment by dalaro** [comment]
@BrynCooke  Please have a look at http://s3.thinkaurelius.com/docs/titan/0.5.3-SNAPSHOT/elasticsearch.html#es-cfg-index-create.  I implemented this by adding a config prefix for arbitrary index creation settings, rather than adding a single Titan option specifically for number_of_replicas.

This is implemented as documented on the titan05 branch.  Unless there are problems, I'll cherry-pick this forward to titan09.  I've been doing duct-tape testing by running curl on /titan/_settings, but I should really add an automated test for this at some point.

**Comment by dalaro** [comment]
I just added a test for this (29491f362521e74f7459aec14c21682589e4050b).  The docs were done last week (ab8f6e5d97721b00c84b67c39d556ddc20d3c2dd).

Barring any objections or suggestions here, I think this is ready to close.  But I'll leave it open until 0.5.3 in case @BrynCooke or anybody else has feedback.

**Comment by BrynCooke** [comment]
Looks good to me. I'll not be able to test until the new year now though.

**Comment by dalaro** [comment]
Great, I'll close this for now.  Please reopen if you run into problems with it or have any related suggestions prior to 0.5.3.
