### ISSUE TITLE
Remove oldfulgora package and contents

### ISSUE THREAD

**Issue by mbroecheler** [thinkaurelius/titan#863]
also remove associated unit tests. This should all be GraphComputer from now on.

**Comment by dalaro** [comment]
As we discussed recently, it turns out that we don't actually want to remove the associated unit tests (as would have been done by #966).  We want to instead port the unit tests forward to the new fulgora interfaces.  I removed oldfulgora but kept the tests in 5b8bcce7f2d645fe3e27a93a18ab5ca34bf86de5.  The tests compile as of that commit, though two of them have problems:
- The pagerank test is `@Ignore`d.  Per offline discussion, we're not going to use the TP3 PR impl, but instead a vertexprogram (could be pagerank, could be something else, just as long as it has an interesting access pattern for testing) written and maintained as part of Titan.  I made #989 for this.
- The TitanPartitionGraphTest of degree counting over partitioned vertices is broken.  This issue seems to be independent of the migration from old to new fulgora.  This method is not `@Ignore`d like the pagerank test, so it still breaks builds.
