### ISSUE TITLE
Array comparison

### ISSUE THREAD

**Issue by mbroecheler** [thinkaurelius/titan#878]
``` scala
  val ip = Array[Byte](127,0,0,1)
  val v = g.addVertex(null)
  v.setProperty("ip", ip)

  println("searching by exact instance")
  if (g.query.has("ip", ip).vertices.iterator.hasNext)
    println("found a matching record")
  else
    println("did not find any records")

  println("searching by same value")
  if (g.query.has("ip", Array[Byte](127,0,0,1)).vertices.iterator.hasNext)
    println("found a matching record")
  else
    println("did not find any records")

```

I suspect Titan does not use Arrays.equals. is this intentional?

**Comment by dalaro** [comment]
Aureliusgraphs posting that led to this issue: https://groups.google.com/d/topic/aureliusgraphs/cxeCd60yhD8/discussion

**Comment by dalaro** [comment]
Tweaked Cmp.EQUAL to pass this test in 50c0998b2a8251779f01e547b8d6a9ca334ed9a4.  The test checks both 1D and 2D arrays.

One potential alternative way to do this: invoke `getClass().isArray()` once inside `has`, store that state somewhere in query object, and later use it to invoke one of two equality check methods -- one for objects, the other for arrays.  But I balked at implementing that, since it seemed much more disruptive than the simpler commit that I pushed.  The commit I pushed does the `isArray` check on every comparison and maintains a single `Cmp.EQUAL`.

This change is just for exact equality.  I didn't touch comparison.
