### ISSUE TITLE
removeProperty() doesn't work

### ISSUE THREAD

**Issue by mbroecheler** [thinkaurelius/titan#893]
when cache-size is set to 0.

Reproducible in 0.5.2. The key is that cache.tx-cache-size must be 0 (for whatever reason you would do that) to see this effect. 

**With cache.tx-cache-size set to default:**

```
gremlin> g = TitanFactory.open("conf/titan-cassandra-es.properties")
==>titangraph[cassandrathrift:[127.0.0.1]]
gremlin> GraphOfTheGodsFactory.load(g)
==>null
gremlin> h = g.V().has('name', 'hercules').next()
==>v[1536]
gremlin> g.rollback()
==>null
gremlin> h.removeProperty('name')
==>hercules
gremlin> h.getProperty('name')
==>null
```

**With cache.tx-cache-size set to 0:**

```
gremlin> g = TitanFactory.open("conf/titan-cassandra-es.properties")
==>titangraph[cassandrathrift:[127.0.0.1]]
gremlin> GraphOfTheGodsFactory.load(g)
==>null
gremlin> h = g.V().has('name', 'hercules').next()
==>v[1536]
gremlin> g.rollback()
==>null
gremlin> h.removeProperty('name')
==>hercules
gremlin> h.getProperty('name')
==>hercules
```

**Comment by dalaro** [comment]
I spent some time stepping through the `h.removeProperty('name')` and `h.getProperty('name')` calls with a debugger.  I think I understand the problem.

Nutshell explanation: GuavaVertexCache evicts the hercules vertex before `cache.get` returns, and in particular, before `removeProperty` has a chance to dirty it.  The GVC eviction listener is responsible for copying dirty evicted vertices to a durable, unlimited-size `volatileVertices` map to prevent just the behavior we're seeing.  This listener is ineffective when it only sees clean vertices right after they are instantiated, before the calling code gets a chance to dirty them, as in the tx-cache-size=0 case.

Here's the explanation with a little bit more detail:

GVC.get calls `cache.get(Long, Retriever<Long, InternalVertex>)` here: https://github.com/thinkaurelius/titan/blob/0.5.2/titan-core/src/main/java/com/thinkaurelius/titan/graphdb/transaction/vertexcache/GuavaVertexCache.java#L69.

Inside this `get` call, `cache` instantiates a new vertex object using the supplied `Retriever`.

Still inside this `get` call, `cache` sees that its size (0) has been exceeded by this just-instantiated vertex, then calls the eviction listener.  The eviction listener checks whether the vertex is dirty on this line: https://github.com/thinkaurelius/titan/blob/0.5.2/titan-core/src/main/java/com/thinkaurelius/titan/graphdb/transaction/vertexcache/GuavaVertexCache.java#L40.  But the `v.isModified()` condition is always false, since every vertex gets evicted right after it's created in its initially-unmodified state.  Hence, vertices are never copied to the `volatileVertices` map.

This behavior makes Titan create one hercules InternalVertex for the `removeProperty` call, then create a separate hercules InternalVertex for the broken `getProperty` calls in the same transaction, leading -- I think -- to the "ghost property" problem.

An aside: `StandardTitanTx.deletedRelations` retains a reference to the deleted property and seems to work more or less as intended on commit, deleting hercules's `name` from the backend.

I'm considering ways to approach this.  However, we can rule out one approach: just setting a low fixed floor on the tx-cache-size (e.g. 1) would not be sufficient.  If the cache size is less than the degree of thread parallelism, then concurrent threads could still run into this problem (depending on how their execution interleaves).

**Comment by dalaro** [comment]
Related commits: a3ea0e5c3cc566984f652619f71b0e058d716909 and af784bd93ef4cbcd8356bd2a255dbcaa2bc4d2a2

As a workaround, I put a minimum of 100 on the effective `cache.tx-cache-size` when the transaction is not read-only.  The assumption behind this workaround is that 100 will be substantially larger than the level of thread parallelism acting on any one transaction.  Read-only transactions are not subject to the minimum.

Application of the minimum is logged at DEBUG.

As mentioned in the commit message for a3ea0e5c3cc566984f652619f71b0e058d716909, it might be possible to eliminate the underlying raciness relatively easily by using a WeakReference-valued hash map and a ReferenceQueue that removes collected value entries from the map. This seemed to do the right thing when I prototyped it, but it's too risky to push in just before a bugfix milestone release.  It's risky because the assumptions about strong references retained by other parts of Titan internals required for correctness are not completely trivial to prove, and because it's not possible to build a completely watertight test, since behavior here is inextricably linked to GC activity.  I opened #915 to consider this or alternative ways to modify GVC to eliminate the underlying race.
