### ISSUE TITLE
A Bug of 0.5.2 ? use closed HConnection in HBaseStoreManager.ensureTableExists()

### ISSUE THREAD

**Issue by christoperzeng** [thinkaurelius/titan#907]
line 1295 of GraphDatabaseConfiguration will call HBaseStoreManager.ensureTableExists() 
the HBaseStoreManager.ensureTableExists() finally close the HBaseAdmin; 
the HBaseStoreManager.cnx will be closed when close the HBaseAdmin;

line 1296 of GraphDatabaseConfiguration will call HBaseStoreManager.ensureTableExists() again, 
this call will use the closed HConnection which cause problems:
the HConnection.masterAddressTracker will reference to the closed HConnection.zookeeper

**Comment by christoperzeng** [comment]
the version of HBase i use is HBase 0.94.2

**Comment by dalaro** [comment]
Those GraphDatabaseConfiguration line numbers seem inconsistent with 0.5.2.  Here's GraphDatabaseConfiguration @ 0.5.2:

https://github.com/thinkaurelius/titan/blob/0.5.2/titan-core/src/main/java/com/thinkaurelius/titan/graphdb/configuration/GraphDatabaseConfiguration.java#L1295-L1296

1296 assigns the `null` literal to a field.  I don't see how that could possibly call `ensureTableExists`.

Is it possible to reproduce this problem?  A config file and script to cause the problem would be great.  If I can trigger the bug, then I can investigate.

**Comment by christoperzeng** [comment]
Sorry, it's my fault. they are line 1259 and 1260
https://github.com/thinkaurelius/titan/blob/0.5.2/titan-core/src/main/java/com/thinkaurelius/titan/graphdb/configuration/GraphDatabaseConfiguration.java#L1259-L1260

**Comment by christoperzeng** [comment]
and it will close HBaseStoreManager.cnx at 
https://github.com/thinkaurelius/titan/blob/0.5.2/titan-hbase-parent/titan-hbase-core/src/main/java/com/thinkaurelius/titan/diskstorage/hbase/HBaseStoreManager.java#L755-L757

**Comment by dalaro** [comment]
@christoperzeng thanks for following up.  I took a closer look.  Lines 1259 and 1260, as you linked in your reply, make sense.  However, I disagree that `HBaseStoreManager.cnx` is closed on HBaseStoreManager.java 755-757.  It's true that we call `HBaseAdmin.close` there.  But we constructed HBaseAdmin using the `HBaseAdmin(HConnection)` constructor (at https://github.com/thinkaurelius/titan/blob/0.5.2/titan-hbase-parent/titan-hbase-core/src/main/java/com/thinkaurelius/titan/diskstorage/hbase/HBaseStoreManager.java#L984-L990).  The source for that constructor shows it setting the final boolean `cleanupConnectionOnClose` field to false.  `HBaseAdmin.close` consults `cleanupConnectionOnClose`; since that's final and was set to false at construction, it should not attempt to close `cnx`.  So this narrative doesn't seem to add up.

I used the source for HBase 0.94.25 when investigating.  0.94.2 is really old.  That might have something to do with it.  I'd be surprised if they changed the connection cleanup behavior in a bugfix release though.

Please reopen if you can provide instructions to reliably reproduce this, or a complete exception stacktrace if you can't reproduce it.  Thanks.
