### ISSUE TITLE
Unclosed transactions escape gremlin scope

### ISSUE THREAD

**Issue by nik9000** [thinkaurelius/titan#911]
I don't know if this is a Gremlin or Titan bug but I'll file it here.  Anyway, at least in 0.5.X, if you start a transaction but don't close it before quitting the server leaks memory.  This crashes Titan:

``` bash
for i in $(seq 1 10); do
  rm -f script
  for j in $(seq 1 1000); do 
    echo 'rexster.getGraph("graph").addVertex();"' $i $j '"' >> script
  done
  echo '?q' >> script
  ./bin/rexster-console.sh < script
done
```

as does this:

``` bash
for i in $(seq 1 10); do
  echo 'g = rexster.getGraph("graph")' > script
  for j in $(seq 1 1000); do 
    echo 'g.getManagementSystem();"' $i $j '"' >> script
  done
  echo '?q' >> script
  ./bin/rexster-console.sh < script
done
```

This isn't really a show stopper bug but it is pretty dangerous.

**Comment by spmallette** [comment]
This is an issue with Rexster. As you mentioned it's not a showstopper in the sense that you just need to be careful that you don't do things in your scripts that let that happen.  

This issue was noted during TP3 development in the creation of Gremlin Server and has been rectified.  When a session with Gremlin Server is closed, the server does a rollback on graphs that support transactions, thus cleaning up.  Interestingly, you show use of `getManagementSystem` which Gremlin Server (nor Rexster) can properly clean up after because it is outside of the TinkerPop API (that is a Titan specific function).  In those cases, you just have to be careful with what you do.

I can look into implementing something similar in Rexster if you would like to create an issue there: https://github.com/tinkerpop/rexster/issues

As this is not a Titan issue, I will close this one.  Thanks.

**Comment by nik9000** [comment]
I think you said that TP3/Titan 0.90 fixes the problem with hanging graph transactions but not hanging management transactions.  Is that right?

I think the hanging management transactions are pretty insidious.  I mean, when I first encountered this I didn't think that I was actually making any transaction because I was just calling `getManagementSystem().getGraphIndex("foo")` to check if the index existed yet.  Its the kind of thing that makes people say "this software is not ready".

**Comment by spmallette** [comment]
> I think you said that TP3/Titan 0.90 fixes the problem with hanging graph transactions but not hanging management transactions. Is that right?

that's right

> I think the hanging management transactions are pretty insidious...Its the kind of thing that makes people say "this software is not ready".

Rexster (or Gremlin Server in TP3) can only operates on the Blueprints API (or Gremlin Structure API in TP3).  It has no knowledge of any APIs outside of that, so from a Rexster/Gremlin Server perspective, I don't have any way to close down the Titan management transaction because to Rexster/Gremlin Server, it's only dealing with the TinkerPop `Graph` interface.

There is the added problem that `ManagmentSystem` is being scoped as a binding in the Rexster/Gremlin Server scriptengine which is outside of the bindings that Rexster/Gremlin Server would know anything about.  I guess what I'm saying is that to have Rexster/Gremlin Server handle `ManagementSystem` well, it would mean some very specific programming to Titan.

Such a thing would likely not be possible with Rexster, but Gremlin Server is a bit more flexibile.  It's likely that Titan could have it's own plugins to Gremlin Server that could perhaps clean up such errant scripts that leave the `ManagementSystem` uncommitted.  I'm not sure if that's a direct that Titan will eventually go or not as we move to Titan 0.9.

Not sure if there are reasons why the `ManagementSystem` is on it's own transaction system or if that could be changed in the future so that it all just falls under the TinkerPop transaction API.  That would be a question for @mbroecheler or @dalaro

**Comment by nik9000** [comment]
> Not sure if there are reasons why the ManagementSystem is on it's own transaction system or if that could be changed in the future so that it all just falls under the TinkerPop transaction API. That would be a question for @mbroecheler or @dalaro

I suppose it'd be possible for gremlin server to expose a registry for transactions opened during the session that implement some simple api that ManagementSystem's transaction implements.  I haven't looked too closely into the code though.

I suppose I'm just concerned that its a bug that almost caused me to stop using Titan at all.  I only stuck with it because I know other people are successfully using it.  It just feels too bad to close with a reason that boils down to "its hard".

**Comment by spmallette** [comment]
I'm not sure that it is has much to do with "hard".  It is more an issue of what TinkerPop looks to expose as a generalization for vendors to implement.  For example, TP3 specifically does not expose any indexing APIs because of the great disparity among the various vendor systems in how they are implemented.  TP3 also chooses not to get into the business of generalizing "schema"  mechanisms for the same reason.  Some things just don't generalize well behind the TinkerPop APIs and thus create greater confusion for users than if we just let people use the specific vendor native APIs.

In TP3, at least, there are greater opportunities for extension by vendors which can allow for specific plugins to the gremlin console and server.  These extension can override the standard TinkerPop features and include vendor-specific code to better deal with these kinds of issues.  We'll need to look into how Titan might be able to take advantage of this in Titan 0.9 and beyond.  Thanks for your feedback.
.
