### ISSUE TITLE
Send back proper error messages

### ISSUE THREAD

**Issue by JPMoresmau** [thinkaurelius/titan#935]
It seems that when using Rexster, a lot of error messages are swallowed and it's impossible to understand what's going on.
I had two concrete cases:
- `Exception during FilterChain execution java.lang.ClassCastException: com.tinkerpop.rexster.protocol.msg.ErrorResponseMessage cannot be cast to org.glassfish.grizzly.asyncqueue.WritableMessage at org.glassfish.grizzly.nio.transport.TCPNIOTransportFilter.handleWrite` while using a debugger showed that it was this issue: https://groups.google.com/forum/#!topic/aureliusgraphs/9fqT8rd1ASo. Somewhere the exception was being treated as a normal return message.
- `com.tinkerpop.rexster.client.RexProException: Script was successfully executed but the result of the script was not properly serialized.` I think (not sure) I get this error because I've set my rexster configuration to query.force-index: true, and the query I run doesn't use any index.

Thanks

**Comment by spmallette** [comment]
Sorry if some of the errors are hard to decipher - whenever I think I have them working nice a new one pops up that isn't.  As this is is not a Titan issue, but related to Rexster, I will close this here.  Please feel free to migrate it to the Rexster project so that it can be addressed in the right place: https://github.com/tinkerpop/rexster/issues  Thanks.

**Comment by JPMoresmau** [comment]
OK, done https://github.com/tinkerpop/rexster/issues/381
