### ISSUE TITLE
When change the TTL of Vertex,Edge,Propery,it can to zero

### ISSUE THREAD

**Issue by boliza** [thinkaurelius/titan#981]
When change the TTL of Vertex,Edge,Propery,it can set to zero.

**Comment by dalaro** [comment]
Let's discuss this in the linked PR (#982) for now.  I just replied there.

**Comment by dalaro** [comment]
Summarizing the discussion in #982: the point of this issue is to allow Titan to remove a finite TTL from an existing type, such that new elements of that type have no TTL.  I don't think #982 can be merged as-is, but the goal is still feasible.

I played with treating `setTTL(-1)` and `getTTL` returning `-1` as indicators of live-forever status on a type, but it was tricky to root out existing assumptions about 0 signifying live-forever, and to interop with Duration, which does not accept negative scalars.  So I stuck with 0 to signify live-forever.  This is implemented, along with three new tests, in the issue_981 branch.

**Comment by dalaro** [comment]
I accidentally wrote #971 instead of #981 into multiple commits on the issue_981 branch.  I rebased it as issue_981_bis to fix those typos.  Matthias answered my only lingering question in that branch about an assertion change (https://github.com/thinkaurelius/titan/commit/addb1559b976c172d8297361c7e9a9ef3d940749#commitcomment-10968686).  I think this is ready to be turned into a PR and merged.

**Comment by dalaro** [comment]
Merged #1069
